// ==============================================================
// RTL generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and OpenCL
// Version: 2019.2
// Copyright (C) 1986-2019 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

`timescale 1 ns / 1 ps 

(* CORE_GENERATION_INFO="box,hls_ip_2019_2,{HLS_INPUT_TYPE=cxx,HLS_INPUT_FLOAT=0,HLS_INPUT_FIXED=1,HLS_INPUT_PART=xc7z020-clg484-1,HLS_INPUT_CLOCK=10.000000,HLS_INPUT_ARCH=dataflow,HLS_SYN_CLOCK=9.005000,HLS_SYN_LAT=-1,HLS_SYN_TPT=-1,HLS_SYN_MEM=6,HLS_SYN_DSP=58,HLS_SYN_FF=10853,HLS_SYN_LUT=11558,HLS_VERSION=2019_2}" *)

module box (
        s_axi_AXILiteS_AWVALID,
        s_axi_AXILiteS_AWREADY,
        s_axi_AXILiteS_AWADDR,
        s_axi_AXILiteS_WVALID,
        s_axi_AXILiteS_WREADY,
        s_axi_AXILiteS_WDATA,
        s_axi_AXILiteS_WSTRB,
        s_axi_AXILiteS_ARVALID,
        s_axi_AXILiteS_ARREADY,
        s_axi_AXILiteS_ARADDR,
        s_axi_AXILiteS_RVALID,
        s_axi_AXILiteS_RREADY,
        s_axi_AXILiteS_RDATA,
        s_axi_AXILiteS_RRESP,
        s_axi_AXILiteS_BVALID,
        s_axi_AXILiteS_BREADY,
        s_axi_AXILiteS_BRESP,
        ap_clk,
        ap_rst_n,
        interrupt,
        buffer_V_Addr_A,
        buffer_V_EN_A,
        buffer_V_Din_A,
        buffer_V_Dout_A,
        buffer_V_WEN_A,
        buffer_V_Clk_A,
        buffer_V_Rst_A,
        buffer_V_Addr_B,
        buffer_V_EN_B,
        buffer_V_Din_B,
        buffer_V_Dout_B,
        buffer_V_WEN_B,
        buffer_V_Clk_B,
        buffer_V_Rst_B,
        video_src_TDATA,
        video_src_TKEEP,
        video_src_TSTRB,
        video_src_TUSER,
        video_src_TLAST,
        video_src_TID,
        video_src_TDEST,
        video_dst_TDATA,
        video_dst_TKEEP,
        video_dst_TSTRB,
        video_dst_TUSER,
        video_dst_TLAST,
        video_dst_TID,
        video_dst_TDEST,
        video_src_TVALID,
        video_src_TREADY,
        video_dst_TVALID,
        video_dst_TREADY
);

parameter    C_S_AXI_AXILITES_DATA_WIDTH = 32;
parameter    C_S_AXI_AXILITES_ADDR_WIDTH = 6;
parameter    C_S_AXI_DATA_WIDTH = 32;
parameter    C_S_AXI_ADDR_WIDTH = 32;

parameter C_S_AXI_AXILITES_WSTRB_WIDTH = (32 / 8);
parameter C_S_AXI_WSTRB_WIDTH = (32 / 8);

input   s_axi_AXILiteS_AWVALID;
output   s_axi_AXILiteS_AWREADY;
input  [C_S_AXI_AXILITES_ADDR_WIDTH - 1:0] s_axi_AXILiteS_AWADDR;
input   s_axi_AXILiteS_WVALID;
output   s_axi_AXILiteS_WREADY;
input  [C_S_AXI_AXILITES_DATA_WIDTH - 1:0] s_axi_AXILiteS_WDATA;
input  [C_S_AXI_AXILITES_WSTRB_WIDTH - 1:0] s_axi_AXILiteS_WSTRB;
input   s_axi_AXILiteS_ARVALID;
output   s_axi_AXILiteS_ARREADY;
input  [C_S_AXI_AXILITES_ADDR_WIDTH - 1:0] s_axi_AXILiteS_ARADDR;
output   s_axi_AXILiteS_RVALID;
input   s_axi_AXILiteS_RREADY;
output  [C_S_AXI_AXILITES_DATA_WIDTH - 1:0] s_axi_AXILiteS_RDATA;
output  [1:0] s_axi_AXILiteS_RRESP;
output   s_axi_AXILiteS_BVALID;
input   s_axi_AXILiteS_BREADY;
output  [1:0] s_axi_AXILiteS_BRESP;
input   ap_clk;
input   ap_rst_n;
output   interrupt;
output  [31:0] buffer_V_Addr_A;
output   buffer_V_EN_A;
output  [31:0] buffer_V_Din_A;
input  [31:0] buffer_V_Dout_A;
output  [3:0] buffer_V_WEN_A;
output   buffer_V_Clk_A;
output   buffer_V_Rst_A;
output  [31:0] buffer_V_Addr_B;
output   buffer_V_EN_B;
output  [31:0] buffer_V_Din_B;
input  [31:0] buffer_V_Dout_B;
output  [3:0] buffer_V_WEN_B;
output   buffer_V_Clk_B;
output   buffer_V_Rst_B;
input  [31:0] video_src_TDATA;
input  [3:0] video_src_TKEEP;
input  [3:0] video_src_TSTRB;
input  [0:0] video_src_TUSER;
input  [0:0] video_src_TLAST;
input  [0:0] video_src_TID;
input  [0:0] video_src_TDEST;
output  [31:0] video_dst_TDATA;
output  [3:0] video_dst_TKEEP;
output  [3:0] video_dst_TSTRB;
output  [0:0] video_dst_TUSER;
output  [0:0] video_dst_TLAST;
output  [0:0] video_dst_TID;
output  [0:0] video_dst_TDEST;
input   video_src_TVALID;
output   video_src_TREADY;
output   video_dst_TVALID;
input   video_dst_TREADY;

 reg    ap_rst_n_inv;
wire    ap_start;
wire    ap_ready;
wire    ap_done;
wire    ap_idle;
wire   [31:0] xleft_s;
wire   [31:0] xright_s;
wire   [31:0] ytop_s;
wire   [31:0] ydown_s;
wire    Block_Mat_exit48_pro_U0_ap_start;
wire    Block_Mat_exit48_pro_U0_start_full_n;
wire    Block_Mat_exit48_pro_U0_ap_done;
wire    Block_Mat_exit48_pro_U0_ap_continue;
wire    Block_Mat_exit48_pro_U0_ap_idle;
wire    Block_Mat_exit48_pro_U0_ap_ready;
wire    Block_Mat_exit48_pro_U0_start_out;
wire    Block_Mat_exit48_pro_U0_start_write;
wire   [31:0] Block_Mat_exit48_pro_U0_xleft_out_din;
wire    Block_Mat_exit48_pro_U0_xleft_out_write;
wire   [31:0] Block_Mat_exit48_pro_U0_xleft_out1_din;
wire    Block_Mat_exit48_pro_U0_xleft_out1_write;
wire   [31:0] Block_Mat_exit48_pro_U0_xright_out_din;
wire    Block_Mat_exit48_pro_U0_xright_out_write;
wire   [31:0] Block_Mat_exit48_pro_U0_xright_out2_din;
wire    Block_Mat_exit48_pro_U0_xright_out2_write;
wire   [31:0] Block_Mat_exit48_pro_U0_ytop_out_din;
wire    Block_Mat_exit48_pro_U0_ytop_out_write;
wire   [31:0] Block_Mat_exit48_pro_U0_ytop_out3_din;
wire    Block_Mat_exit48_pro_U0_ytop_out3_write;
wire   [31:0] Block_Mat_exit48_pro_U0_ydown_out_din;
wire    Block_Mat_exit48_pro_U0_ydown_out_write;
wire   [31:0] Block_Mat_exit48_pro_U0_ydown_out4_din;
wire    Block_Mat_exit48_pro_U0_ydown_out4_write;
wire   [10:0] Block_Mat_exit48_pro_U0_rgb_img_rows_V_out_din;
wire    Block_Mat_exit48_pro_U0_rgb_img_rows_V_out_write;
wire   [11:0] Block_Mat_exit48_pro_U0_rgb_img_cols_V_out_din;
wire    Block_Mat_exit48_pro_U0_rgb_img_cols_V_out_write;
wire   [31:0] Block_Mat_exit48_pro_U0_plate_rows_V_out_din;
wire    Block_Mat_exit48_pro_U0_plate_rows_V_out_write;
wire   [31:0] Block_Mat_exit48_pro_U0_plate_cols_V_out_din;
wire    Block_Mat_exit48_pro_U0_plate_cols_V_out_write;
wire    AXIvideo2Mat_U0_ap_start;
wire    AXIvideo2Mat_U0_ap_done;
wire    AXIvideo2Mat_U0_ap_continue;
wire    AXIvideo2Mat_U0_ap_idle;
wire    AXIvideo2Mat_U0_ap_ready;
wire    AXIvideo2Mat_U0_start_out;
wire    AXIvideo2Mat_U0_start_write;
wire    AXIvideo2Mat_U0_video_src_TREADY;
wire    AXIvideo2Mat_U0_img_rows_V_read;
wire    AXIvideo2Mat_U0_img_cols_V_read;
wire   [7:0] AXIvideo2Mat_U0_img_data_stream_0_V_din;
wire    AXIvideo2Mat_U0_img_data_stream_0_V_write;
wire   [7:0] AXIvideo2Mat_U0_img_data_stream_1_V_din;
wire    AXIvideo2Mat_U0_img_data_stream_1_V_write;
wire   [7:0] AXIvideo2Mat_U0_img_data_stream_2_V_din;
wire    AXIvideo2Mat_U0_img_data_stream_2_V_write;
wire   [10:0] AXIvideo2Mat_U0_img_rows_V_out_din;
wire    AXIvideo2Mat_U0_img_rows_V_out_write;
wire   [11:0] AXIvideo2Mat_U0_img_cols_V_out_din;
wire    AXIvideo2Mat_U0_img_cols_V_out_write;
wire    Duplicate_U0_ap_start;
wire    Duplicate_U0_ap_done;
wire    Duplicate_U0_ap_continue;
wire    Duplicate_U0_ap_idle;
wire    Duplicate_U0_ap_ready;
wire    Duplicate_U0_src_rows_V_read;
wire    Duplicate_U0_src_cols_V_read;
wire    Duplicate_U0_src_data_stream_0_V_read;
wire    Duplicate_U0_src_data_stream_1_V_read;
wire    Duplicate_U0_src_data_stream_2_V_read;
wire   [7:0] Duplicate_U0_dst1_data_stream_0_V_din;
wire    Duplicate_U0_dst1_data_stream_0_V_write;
wire   [7:0] Duplicate_U0_dst1_data_stream_1_V_din;
wire    Duplicate_U0_dst1_data_stream_1_V_write;
wire   [7:0] Duplicate_U0_dst1_data_stream_2_V_din;
wire    Duplicate_U0_dst1_data_stream_2_V_write;
wire   [7:0] Duplicate_U0_dst2_data_stream_0_V_din;
wire    Duplicate_U0_dst2_data_stream_0_V_write;
wire   [7:0] Duplicate_U0_dst2_data_stream_1_V_din;
wire    Duplicate_U0_dst2_data_stream_1_V_write;
wire   [7:0] Duplicate_U0_dst2_data_stream_2_V_din;
wire    Duplicate_U0_dst2_data_stream_2_V_write;
wire    Return_Plate_U0_ap_start;
wire    Return_Plate_U0_ap_done;
wire    Return_Plate_U0_ap_continue;
wire    Return_Plate_U0_ap_idle;
wire    Return_Plate_U0_ap_ready;
wire    Return_Plate_U0_input_img_data_stream_0_V_read;
wire    Return_Plate_U0_input_img_data_stream_1_V_read;
wire    Return_Plate_U0_input_img_data_stream_2_V_read;
wire   [7:0] Return_Plate_U0_output_plate_data_stream_0_V_din;
wire    Return_Plate_U0_output_plate_data_stream_0_V_write;
wire   [7:0] Return_Plate_U0_output_plate_data_stream_1_V_din;
wire    Return_Plate_U0_output_plate_data_stream_1_V_write;
wire   [7:0] Return_Plate_U0_output_plate_data_stream_2_V_din;
wire    Return_Plate_U0_output_plate_data_stream_2_V_write;
wire    Return_Plate_U0_xleft_read;
wire    Return_Plate_U0_xright_read;
wire    Return_Plate_U0_ytop_read;
wire    Return_Plate_U0_ydown_read;
wire    Resize_U0_ap_start;
wire    Resize_U0_ap_done;
wire    Resize_U0_ap_continue;
wire    Resize_U0_ap_idle;
wire    Resize_U0_ap_ready;
wire    Resize_U0_start_out;
wire    Resize_U0_start_write;
wire    Resize_U0_p_src_rows_V_read;
wire    Resize_U0_p_src_cols_V_read;
wire    Resize_U0_p_src_data_stream_0_V_read;
wire    Resize_U0_p_src_data_stream_1_V_read;
wire    Resize_U0_p_src_data_stream_2_V_read;
wire   [7:0] Resize_U0_p_dst_data_stream_0_V_din;
wire    Resize_U0_p_dst_data_stream_0_V_write;
wire   [7:0] Resize_U0_p_dst_data_stream_1_V_din;
wire    Resize_U0_p_dst_data_stream_1_V_write;
wire   [7:0] Resize_U0_p_dst_data_stream_2_V_din;
wire    Resize_U0_p_dst_data_stream_2_V_write;
wire    Loop_BRAM_LOOP_proc7_U0_ap_start;
wire    Loop_BRAM_LOOP_proc7_U0_ap_done;
wire    Loop_BRAM_LOOP_proc7_U0_ap_continue;
wire    Loop_BRAM_LOOP_proc7_U0_ap_idle;
wire    Loop_BRAM_LOOP_proc7_U0_ap_ready;
wire    Loop_BRAM_LOOP_proc7_U0_standard_plate_data_stream_0_V_read;
wire    Loop_BRAM_LOOP_proc7_U0_standard_plate_data_stream_1_V_read;
wire    Loop_BRAM_LOOP_proc7_U0_standard_plate_data_stream_2_V_read;
wire   [31:0] Loop_BRAM_LOOP_proc7_U0_buffer_V_Addr_A;
wire    Loop_BRAM_LOOP_proc7_U0_buffer_V_EN_A;
wire   [3:0] Loop_BRAM_LOOP_proc7_U0_buffer_V_WEN_A;
wire   [31:0] Loop_BRAM_LOOP_proc7_U0_buffer_V_Din_A;
wire    ap_sync_continue;
wire    Add_Rectangle_U0_ap_start;
wire    Add_Rectangle_U0_ap_done;
wire    Add_Rectangle_U0_ap_continue;
wire    Add_Rectangle_U0_ap_idle;
wire    Add_Rectangle_U0_ap_ready;
wire    Add_Rectangle_U0_start_out;
wire    Add_Rectangle_U0_start_write;
wire    Add_Rectangle_U0_src_data_stream_0_V_read;
wire    Add_Rectangle_U0_src_data_stream_1_V_read;
wire    Add_Rectangle_U0_src_data_stream_2_V_read;
wire   [7:0] Add_Rectangle_U0_dst_data_stream_0_V_din;
wire    Add_Rectangle_U0_dst_data_stream_0_V_write;
wire   [7:0] Add_Rectangle_U0_dst_data_stream_1_V_din;
wire    Add_Rectangle_U0_dst_data_stream_1_V_write;
wire   [7:0] Add_Rectangle_U0_dst_data_stream_2_V_din;
wire    Add_Rectangle_U0_dst_data_stream_2_V_write;
wire    Add_Rectangle_U0_xleft_read;
wire    Add_Rectangle_U0_xright_read;
wire    Add_Rectangle_U0_ytop_read;
wire    Add_Rectangle_U0_ydown_read;
wire    Mat2AXIvideo_U0_ap_start;
wire    Mat2AXIvideo_U0_ap_done;
wire    Mat2AXIvideo_U0_ap_continue;
wire    Mat2AXIvideo_U0_ap_idle;
wire    Mat2AXIvideo_U0_ap_ready;
wire    Mat2AXIvideo_U0_img_data_stream_0_V_read;
wire    Mat2AXIvideo_U0_img_data_stream_1_V_read;
wire    Mat2AXIvideo_U0_img_data_stream_2_V_read;
wire   [31:0] Mat2AXIvideo_U0_video_dst_TDATA;
wire    Mat2AXIvideo_U0_video_dst_TVALID;
wire   [3:0] Mat2AXIvideo_U0_video_dst_TKEEP;
wire   [3:0] Mat2AXIvideo_U0_video_dst_TSTRB;
wire   [0:0] Mat2AXIvideo_U0_video_dst_TUSER;
wire   [0:0] Mat2AXIvideo_U0_video_dst_TLAST;
wire   [0:0] Mat2AXIvideo_U0_video_dst_TID;
wire   [0:0] Mat2AXIvideo_U0_video_dst_TDEST;
wire    xleft_c_full_n;
wire   [31:0] xleft_c_dout;
wire    xleft_c_empty_n;
wire    xleft_c59_full_n;
wire   [31:0] xleft_c59_dout;
wire    xleft_c59_empty_n;
wire    xright_c_full_n;
wire   [31:0] xright_c_dout;
wire    xright_c_empty_n;
wire    xright_c60_full_n;
wire   [31:0] xright_c60_dout;
wire    xright_c60_empty_n;
wire    ytop_c_full_n;
wire   [31:0] ytop_c_dout;
wire    ytop_c_empty_n;
wire    ytop_c61_full_n;
wire   [31:0] ytop_c61_dout;
wire    ytop_c61_empty_n;
wire    ydown_c_full_n;
wire   [31:0] ydown_c_dout;
wire    ydown_c_empty_n;
wire    ydown_c62_full_n;
wire   [31:0] ydown_c62_dout;
wire    ydown_c62_empty_n;
wire    rgb_img_rows_V_c_full_n;
wire   [10:0] rgb_img_rows_V_c_dout;
wire    rgb_img_rows_V_c_empty_n;
wire    rgb_img_cols_V_c_full_n;
wire   [11:0] rgb_img_cols_V_c_dout;
wire    rgb_img_cols_V_c_empty_n;
wire    plate_rows_V_c_full_n;
wire   [31:0] plate_rows_V_c_dout;
wire    plate_rows_V_c_empty_n;
wire    plate_cols_V_c_full_n;
wire   [31:0] plate_cols_V_c_dout;
wire    plate_cols_V_c_empty_n;
wire    rgb_img_data_stream_s_full_n;
wire   [7:0] rgb_img_data_stream_s_dout;
wire    rgb_img_data_stream_s_empty_n;
wire    rgb_img_data_stream_1_full_n;
wire   [7:0] rgb_img_data_stream_1_dout;
wire    rgb_img_data_stream_1_empty_n;
wire    rgb_img_data_stream_2_full_n;
wire   [7:0] rgb_img_data_stream_2_dout;
wire    rgb_img_data_stream_2_empty_n;
wire    rgb_img_rows_V_c63_full_n;
wire   [10:0] rgb_img_rows_V_c63_dout;
wire    rgb_img_rows_V_c63_empty_n;
wire    rgb_img_cols_V_c64_full_n;
wire   [11:0] rgb_img_cols_V_c64_dout;
wire    rgb_img_cols_V_c64_empty_n;
wire    copy1_data_stream_0_full_n;
wire   [7:0] copy1_data_stream_0_dout;
wire    copy1_data_stream_0_empty_n;
wire    copy1_data_stream_1_full_n;
wire   [7:0] copy1_data_stream_1_dout;
wire    copy1_data_stream_1_empty_n;
wire    copy1_data_stream_2_full_n;
wire   [7:0] copy1_data_stream_2_dout;
wire    copy1_data_stream_2_empty_n;
wire    copy2_data_stream_0_full_n;
wire   [7:0] copy2_data_stream_0_dout;
wire    copy2_data_stream_0_empty_n;
wire    copy2_data_stream_1_full_n;
wire   [7:0] copy2_data_stream_1_dout;
wire    copy2_data_stream_1_empty_n;
wire    copy2_data_stream_2_full_n;
wire   [7:0] copy2_data_stream_2_dout;
wire    copy2_data_stream_2_empty_n;
wire    plate_data_stream_0_full_n;
wire   [7:0] plate_data_stream_0_dout;
wire    plate_data_stream_0_empty_n;
wire    plate_data_stream_1_full_n;
wire   [7:0] plate_data_stream_1_dout;
wire    plate_data_stream_1_empty_n;
wire    plate_data_stream_2_full_n;
wire   [7:0] plate_data_stream_2_dout;
wire    plate_data_stream_2_empty_n;
wire    standard_plate_data_s_full_n;
wire   [7:0] standard_plate_data_s_dout;
wire    standard_plate_data_s_empty_n;
wire    standard_plate_data_1_full_n;
wire   [7:0] standard_plate_data_1_dout;
wire    standard_plate_data_1_empty_n;
wire    standard_plate_data_2_full_n;
wire   [7:0] standard_plate_data_2_dout;
wire    standard_plate_data_2_empty_n;
wire    output_img_data_stre_full_n;
wire   [7:0] output_img_data_stre_dout;
wire    output_img_data_stre_empty_n;
wire    output_img_data_stre_1_full_n;
wire   [7:0] output_img_data_stre_1_dout;
wire    output_img_data_stre_1_empty_n;
wire    output_img_data_stre_2_full_n;
wire   [7:0] output_img_data_stre_2_dout;
wire    output_img_data_stre_2_empty_n;
wire    ap_sync_done;
wire    ap_sync_ready;
reg    ap_sync_reg_Block_Mat_exit48_pro_U0_ap_ready;
wire    ap_sync_Block_Mat_exit48_pro_U0_ap_ready;
reg   [1:0] Block_Mat_exit48_pro_U0_ap_ready_count;
reg    ap_sync_reg_AXIvideo2Mat_U0_ap_ready;
wire    ap_sync_AXIvideo2Mat_U0_ap_ready;
reg   [1:0] AXIvideo2Mat_U0_ap_ready_count;
wire   [0:0] start_for_Return_Plate_U0_din;
wire    start_for_Return_Plate_U0_full_n;
wire   [0:0] start_for_Return_Plate_U0_dout;
wire    start_for_Return_Plate_U0_empty_n;
wire   [0:0] start_for_Resize_U0_din;
wire    start_for_Resize_U0_full_n;
wire   [0:0] start_for_Resize_U0_dout;
wire    start_for_Resize_U0_empty_n;
wire   [0:0] start_for_Add_Rectangle_U0_din;
wire    start_for_Add_Rectangle_U0_full_n;
wire   [0:0] start_for_Add_Rectangle_U0_dout;
wire    start_for_Add_Rectangle_U0_empty_n;
wire   [0:0] start_for_Duplicate_U0_din;
wire    start_for_Duplicate_U0_full_n;
wire   [0:0] start_for_Duplicate_U0_dout;
wire    start_for_Duplicate_U0_empty_n;
wire    Duplicate_U0_start_full_n;
wire    Duplicate_U0_start_write;
wire    Return_Plate_U0_start_full_n;
wire    Return_Plate_U0_start_write;
wire   [0:0] start_for_Loop_BRAM_LOOP_proc7_U0_din;
wire    start_for_Loop_BRAM_LOOP_proc7_U0_full_n;
wire   [0:0] start_for_Loop_BRAM_LOOP_proc7_U0_dout;
wire    start_for_Loop_BRAM_LOOP_proc7_U0_empty_n;
wire    Loop_BRAM_LOOP_proc7_U0_start_full_n;
wire    Loop_BRAM_LOOP_proc7_U0_start_write;
wire   [0:0] start_for_Mat2AXIvideo_U0_din;
wire    start_for_Mat2AXIvideo_U0_full_n;
wire   [0:0] start_for_Mat2AXIvideo_U0_dout;
wire    start_for_Mat2AXIvideo_U0_empty_n;
wire    Mat2AXIvideo_U0_start_full_n;
wire    Mat2AXIvideo_U0_start_write;

// power-on initialization
initial begin
#0 ap_sync_reg_Block_Mat_exit48_pro_U0_ap_ready = 1'b0;
#0 Block_Mat_exit48_pro_U0_ap_ready_count = 2'd0;
#0 ap_sync_reg_AXIvideo2Mat_U0_ap_ready = 1'b0;
#0 AXIvideo2Mat_U0_ap_ready_count = 2'd0;
end

box_AXILiteS_s_axi #(
    .C_S_AXI_ADDR_WIDTH( C_S_AXI_AXILITES_ADDR_WIDTH ),
    .C_S_AXI_DATA_WIDTH( C_S_AXI_AXILITES_DATA_WIDTH ))
box_AXILiteS_s_axi_U(
    .AWVALID(s_axi_AXILiteS_AWVALID),
    .AWREADY(s_axi_AXILiteS_AWREADY),
    .AWADDR(s_axi_AXILiteS_AWADDR),
    .WVALID(s_axi_AXILiteS_WVALID),
    .WREADY(s_axi_AXILiteS_WREADY),
    .WDATA(s_axi_AXILiteS_WDATA),
    .WSTRB(s_axi_AXILiteS_WSTRB),
    .ARVALID(s_axi_AXILiteS_ARVALID),
    .ARREADY(s_axi_AXILiteS_ARREADY),
    .ARADDR(s_axi_AXILiteS_ARADDR),
    .RVALID(s_axi_AXILiteS_RVALID),
    .RREADY(s_axi_AXILiteS_RREADY),
    .RDATA(s_axi_AXILiteS_RDATA),
    .RRESP(s_axi_AXILiteS_RRESP),
    .BVALID(s_axi_AXILiteS_BVALID),
    .BREADY(s_axi_AXILiteS_BREADY),
    .BRESP(s_axi_AXILiteS_BRESP),
    .ACLK(ap_clk),
    .ARESET(ap_rst_n_inv),
    .ACLK_EN(1'b1),
    .ap_start(ap_start),
    .interrupt(interrupt),
    .ap_ready(ap_ready),
    .ap_done(ap_done),
    .ap_idle(ap_idle),
    .xleft_s(xleft_s),
    .xright_s(xright_s),
    .ytop_s(ytop_s),
    .ydown_s(ydown_s)
);

Block_Mat_exit48_pro Block_Mat_exit48_pro_U0(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .ap_start(Block_Mat_exit48_pro_U0_ap_start),
    .start_full_n(Block_Mat_exit48_pro_U0_start_full_n),
    .ap_done(Block_Mat_exit48_pro_U0_ap_done),
    .ap_continue(Block_Mat_exit48_pro_U0_ap_continue),
    .ap_idle(Block_Mat_exit48_pro_U0_ap_idle),
    .ap_ready(Block_Mat_exit48_pro_U0_ap_ready),
    .start_out(Block_Mat_exit48_pro_U0_start_out),
    .start_write(Block_Mat_exit48_pro_U0_start_write),
    .xleft_s(xleft_s),
    .xright_s(xright_s),
    .ytop_s(ytop_s),
    .ydown_s(ydown_s),
    .xleft_out_din(Block_Mat_exit48_pro_U0_xleft_out_din),
    .xleft_out_full_n(xleft_c_full_n),
    .xleft_out_write(Block_Mat_exit48_pro_U0_xleft_out_write),
    .xleft_out1_din(Block_Mat_exit48_pro_U0_xleft_out1_din),
    .xleft_out1_full_n(xleft_c59_full_n),
    .xleft_out1_write(Block_Mat_exit48_pro_U0_xleft_out1_write),
    .xright_out_din(Block_Mat_exit48_pro_U0_xright_out_din),
    .xright_out_full_n(xright_c_full_n),
    .xright_out_write(Block_Mat_exit48_pro_U0_xright_out_write),
    .xright_out2_din(Block_Mat_exit48_pro_U0_xright_out2_din),
    .xright_out2_full_n(xright_c60_full_n),
    .xright_out2_write(Block_Mat_exit48_pro_U0_xright_out2_write),
    .ytop_out_din(Block_Mat_exit48_pro_U0_ytop_out_din),
    .ytop_out_full_n(ytop_c_full_n),
    .ytop_out_write(Block_Mat_exit48_pro_U0_ytop_out_write),
    .ytop_out3_din(Block_Mat_exit48_pro_U0_ytop_out3_din),
    .ytop_out3_full_n(ytop_c61_full_n),
    .ytop_out3_write(Block_Mat_exit48_pro_U0_ytop_out3_write),
    .ydown_out_din(Block_Mat_exit48_pro_U0_ydown_out_din),
    .ydown_out_full_n(ydown_c_full_n),
    .ydown_out_write(Block_Mat_exit48_pro_U0_ydown_out_write),
    .ydown_out4_din(Block_Mat_exit48_pro_U0_ydown_out4_din),
    .ydown_out4_full_n(ydown_c62_full_n),
    .ydown_out4_write(Block_Mat_exit48_pro_U0_ydown_out4_write),
    .rgb_img_rows_V_out_din(Block_Mat_exit48_pro_U0_rgb_img_rows_V_out_din),
    .rgb_img_rows_V_out_full_n(rgb_img_rows_V_c_full_n),
    .rgb_img_rows_V_out_write(Block_Mat_exit48_pro_U0_rgb_img_rows_V_out_write),
    .rgb_img_cols_V_out_din(Block_Mat_exit48_pro_U0_rgb_img_cols_V_out_din),
    .rgb_img_cols_V_out_full_n(rgb_img_cols_V_c_full_n),
    .rgb_img_cols_V_out_write(Block_Mat_exit48_pro_U0_rgb_img_cols_V_out_write),
    .plate_rows_V_out_din(Block_Mat_exit48_pro_U0_plate_rows_V_out_din),
    .plate_rows_V_out_full_n(plate_rows_V_c_full_n),
    .plate_rows_V_out_write(Block_Mat_exit48_pro_U0_plate_rows_V_out_write),
    .plate_cols_V_out_din(Block_Mat_exit48_pro_U0_plate_cols_V_out_din),
    .plate_cols_V_out_full_n(plate_cols_V_c_full_n),
    .plate_cols_V_out_write(Block_Mat_exit48_pro_U0_plate_cols_V_out_write)
);

AXIvideo2Mat AXIvideo2Mat_U0(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .ap_start(AXIvideo2Mat_U0_ap_start),
    .start_full_n(start_for_Duplicate_U0_full_n),
    .ap_done(AXIvideo2Mat_U0_ap_done),
    .ap_continue(AXIvideo2Mat_U0_ap_continue),
    .ap_idle(AXIvideo2Mat_U0_ap_idle),
    .ap_ready(AXIvideo2Mat_U0_ap_ready),
    .start_out(AXIvideo2Mat_U0_start_out),
    .start_write(AXIvideo2Mat_U0_start_write),
    .video_src_TDATA(video_src_TDATA),
    .video_src_TVALID(video_src_TVALID),
    .video_src_TREADY(AXIvideo2Mat_U0_video_src_TREADY),
    .video_src_TKEEP(video_src_TKEEP),
    .video_src_TSTRB(video_src_TSTRB),
    .video_src_TUSER(video_src_TUSER),
    .video_src_TLAST(video_src_TLAST),
    .video_src_TID(video_src_TID),
    .video_src_TDEST(video_src_TDEST),
    .img_rows_V_dout(rgb_img_rows_V_c_dout),
    .img_rows_V_empty_n(rgb_img_rows_V_c_empty_n),
    .img_rows_V_read(AXIvideo2Mat_U0_img_rows_V_read),
    .img_cols_V_dout(rgb_img_cols_V_c_dout),
    .img_cols_V_empty_n(rgb_img_cols_V_c_empty_n),
    .img_cols_V_read(AXIvideo2Mat_U0_img_cols_V_read),
    .img_data_stream_0_V_din(AXIvideo2Mat_U0_img_data_stream_0_V_din),
    .img_data_stream_0_V_full_n(rgb_img_data_stream_s_full_n),
    .img_data_stream_0_V_write(AXIvideo2Mat_U0_img_data_stream_0_V_write),
    .img_data_stream_1_V_din(AXIvideo2Mat_U0_img_data_stream_1_V_din),
    .img_data_stream_1_V_full_n(rgb_img_data_stream_1_full_n),
    .img_data_stream_1_V_write(AXIvideo2Mat_U0_img_data_stream_1_V_write),
    .img_data_stream_2_V_din(AXIvideo2Mat_U0_img_data_stream_2_V_din),
    .img_data_stream_2_V_full_n(rgb_img_data_stream_2_full_n),
    .img_data_stream_2_V_write(AXIvideo2Mat_U0_img_data_stream_2_V_write),
    .img_rows_V_out_din(AXIvideo2Mat_U0_img_rows_V_out_din),
    .img_rows_V_out_full_n(rgb_img_rows_V_c63_full_n),
    .img_rows_V_out_write(AXIvideo2Mat_U0_img_rows_V_out_write),
    .img_cols_V_out_din(AXIvideo2Mat_U0_img_cols_V_out_din),
    .img_cols_V_out_full_n(rgb_img_cols_V_c64_full_n),
    .img_cols_V_out_write(AXIvideo2Mat_U0_img_cols_V_out_write)
);

Duplicate Duplicate_U0(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .ap_start(Duplicate_U0_ap_start),
    .ap_done(Duplicate_U0_ap_done),
    .ap_continue(Duplicate_U0_ap_continue),
    .ap_idle(Duplicate_U0_ap_idle),
    .ap_ready(Duplicate_U0_ap_ready),
    .src_rows_V_dout(rgb_img_rows_V_c63_dout),
    .src_rows_V_empty_n(rgb_img_rows_V_c63_empty_n),
    .src_rows_V_read(Duplicate_U0_src_rows_V_read),
    .src_cols_V_dout(rgb_img_cols_V_c64_dout),
    .src_cols_V_empty_n(rgb_img_cols_V_c64_empty_n),
    .src_cols_V_read(Duplicate_U0_src_cols_V_read),
    .src_data_stream_0_V_dout(rgb_img_data_stream_s_dout),
    .src_data_stream_0_V_empty_n(rgb_img_data_stream_s_empty_n),
    .src_data_stream_0_V_read(Duplicate_U0_src_data_stream_0_V_read),
    .src_data_stream_1_V_dout(rgb_img_data_stream_1_dout),
    .src_data_stream_1_V_empty_n(rgb_img_data_stream_1_empty_n),
    .src_data_stream_1_V_read(Duplicate_U0_src_data_stream_1_V_read),
    .src_data_stream_2_V_dout(rgb_img_data_stream_2_dout),
    .src_data_stream_2_V_empty_n(rgb_img_data_stream_2_empty_n),
    .src_data_stream_2_V_read(Duplicate_U0_src_data_stream_2_V_read),
    .dst1_data_stream_0_V_din(Duplicate_U0_dst1_data_stream_0_V_din),
    .dst1_data_stream_0_V_full_n(copy1_data_stream_0_full_n),
    .dst1_data_stream_0_V_write(Duplicate_U0_dst1_data_stream_0_V_write),
    .dst1_data_stream_1_V_din(Duplicate_U0_dst1_data_stream_1_V_din),
    .dst1_data_stream_1_V_full_n(copy1_data_stream_1_full_n),
    .dst1_data_stream_1_V_write(Duplicate_U0_dst1_data_stream_1_V_write),
    .dst1_data_stream_2_V_din(Duplicate_U0_dst1_data_stream_2_V_din),
    .dst1_data_stream_2_V_full_n(copy1_data_stream_2_full_n),
    .dst1_data_stream_2_V_write(Duplicate_U0_dst1_data_stream_2_V_write),
    .dst2_data_stream_0_V_din(Duplicate_U0_dst2_data_stream_0_V_din),
    .dst2_data_stream_0_V_full_n(copy2_data_stream_0_full_n),
    .dst2_data_stream_0_V_write(Duplicate_U0_dst2_data_stream_0_V_write),
    .dst2_data_stream_1_V_din(Duplicate_U0_dst2_data_stream_1_V_din),
    .dst2_data_stream_1_V_full_n(copy2_data_stream_1_full_n),
    .dst2_data_stream_1_V_write(Duplicate_U0_dst2_data_stream_1_V_write),
    .dst2_data_stream_2_V_din(Duplicate_U0_dst2_data_stream_2_V_din),
    .dst2_data_stream_2_V_full_n(copy2_data_stream_2_full_n),
    .dst2_data_stream_2_V_write(Duplicate_U0_dst2_data_stream_2_V_write)
);

Return_Plate Return_Plate_U0(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .ap_start(Return_Plate_U0_ap_start),
    .ap_done(Return_Plate_U0_ap_done),
    .ap_continue(Return_Plate_U0_ap_continue),
    .ap_idle(Return_Plate_U0_ap_idle),
    .ap_ready(Return_Plate_U0_ap_ready),
    .input_img_data_stream_0_V_dout(copy1_data_stream_0_dout),
    .input_img_data_stream_0_V_empty_n(copy1_data_stream_0_empty_n),
    .input_img_data_stream_0_V_read(Return_Plate_U0_input_img_data_stream_0_V_read),
    .input_img_data_stream_1_V_dout(copy1_data_stream_1_dout),
    .input_img_data_stream_1_V_empty_n(copy1_data_stream_1_empty_n),
    .input_img_data_stream_1_V_read(Return_Plate_U0_input_img_data_stream_1_V_read),
    .input_img_data_stream_2_V_dout(copy1_data_stream_2_dout),
    .input_img_data_stream_2_V_empty_n(copy1_data_stream_2_empty_n),
    .input_img_data_stream_2_V_read(Return_Plate_U0_input_img_data_stream_2_V_read),
    .output_plate_data_stream_0_V_din(Return_Plate_U0_output_plate_data_stream_0_V_din),
    .output_plate_data_stream_0_V_full_n(plate_data_stream_0_full_n),
    .output_plate_data_stream_0_V_write(Return_Plate_U0_output_plate_data_stream_0_V_write),
    .output_plate_data_stream_1_V_din(Return_Plate_U0_output_plate_data_stream_1_V_din),
    .output_plate_data_stream_1_V_full_n(plate_data_stream_1_full_n),
    .output_plate_data_stream_1_V_write(Return_Plate_U0_output_plate_data_stream_1_V_write),
    .output_plate_data_stream_2_V_din(Return_Plate_U0_output_plate_data_stream_2_V_din),
    .output_plate_data_stream_2_V_full_n(plate_data_stream_2_full_n),
    .output_plate_data_stream_2_V_write(Return_Plate_U0_output_plate_data_stream_2_V_write),
    .xleft_dout(xleft_c_dout),
    .xleft_empty_n(xleft_c_empty_n),
    .xleft_read(Return_Plate_U0_xleft_read),
    .xright_dout(xright_c_dout),
    .xright_empty_n(xright_c_empty_n),
    .xright_read(Return_Plate_U0_xright_read),
    .ytop_dout(ytop_c_dout),
    .ytop_empty_n(ytop_c_empty_n),
    .ytop_read(Return_Plate_U0_ytop_read),
    .ydown_dout(ydown_c_dout),
    .ydown_empty_n(ydown_c_empty_n),
    .ydown_read(Return_Plate_U0_ydown_read)
);

Resize Resize_U0(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .ap_start(Resize_U0_ap_start),
    .start_full_n(start_for_Loop_BRAM_LOOP_proc7_U0_full_n),
    .ap_done(Resize_U0_ap_done),
    .ap_continue(Resize_U0_ap_continue),
    .ap_idle(Resize_U0_ap_idle),
    .ap_ready(Resize_U0_ap_ready),
    .start_out(Resize_U0_start_out),
    .start_write(Resize_U0_start_write),
    .p_src_rows_V_dout(plate_rows_V_c_dout),
    .p_src_rows_V_empty_n(plate_rows_V_c_empty_n),
    .p_src_rows_V_read(Resize_U0_p_src_rows_V_read),
    .p_src_cols_V_dout(plate_cols_V_c_dout),
    .p_src_cols_V_empty_n(plate_cols_V_c_empty_n),
    .p_src_cols_V_read(Resize_U0_p_src_cols_V_read),
    .p_src_data_stream_0_V_dout(plate_data_stream_0_dout),
    .p_src_data_stream_0_V_empty_n(plate_data_stream_0_empty_n),
    .p_src_data_stream_0_V_read(Resize_U0_p_src_data_stream_0_V_read),
    .p_src_data_stream_1_V_dout(plate_data_stream_1_dout),
    .p_src_data_stream_1_V_empty_n(plate_data_stream_1_empty_n),
    .p_src_data_stream_1_V_read(Resize_U0_p_src_data_stream_1_V_read),
    .p_src_data_stream_2_V_dout(plate_data_stream_2_dout),
    .p_src_data_stream_2_V_empty_n(plate_data_stream_2_empty_n),
    .p_src_data_stream_2_V_read(Resize_U0_p_src_data_stream_2_V_read),
    .p_dst_data_stream_0_V_din(Resize_U0_p_dst_data_stream_0_V_din),
    .p_dst_data_stream_0_V_full_n(standard_plate_data_s_full_n),
    .p_dst_data_stream_0_V_write(Resize_U0_p_dst_data_stream_0_V_write),
    .p_dst_data_stream_1_V_din(Resize_U0_p_dst_data_stream_1_V_din),
    .p_dst_data_stream_1_V_full_n(standard_plate_data_1_full_n),
    .p_dst_data_stream_1_V_write(Resize_U0_p_dst_data_stream_1_V_write),
    .p_dst_data_stream_2_V_din(Resize_U0_p_dst_data_stream_2_V_din),
    .p_dst_data_stream_2_V_full_n(standard_plate_data_2_full_n),
    .p_dst_data_stream_2_V_write(Resize_U0_p_dst_data_stream_2_V_write)
);

Loop_BRAM_LOOP_proc7 Loop_BRAM_LOOP_proc7_U0(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .ap_start(Loop_BRAM_LOOP_proc7_U0_ap_start),
    .ap_done(Loop_BRAM_LOOP_proc7_U0_ap_done),
    .ap_continue(Loop_BRAM_LOOP_proc7_U0_ap_continue),
    .ap_idle(Loop_BRAM_LOOP_proc7_U0_ap_idle),
    .ap_ready(Loop_BRAM_LOOP_proc7_U0_ap_ready),
    .standard_plate_data_stream_0_V_dout(standard_plate_data_s_dout),
    .standard_plate_data_stream_0_V_empty_n(standard_plate_data_s_empty_n),
    .standard_plate_data_stream_0_V_read(Loop_BRAM_LOOP_proc7_U0_standard_plate_data_stream_0_V_read),
    .standard_plate_data_stream_1_V_dout(standard_plate_data_1_dout),
    .standard_plate_data_stream_1_V_empty_n(standard_plate_data_1_empty_n),
    .standard_plate_data_stream_1_V_read(Loop_BRAM_LOOP_proc7_U0_standard_plate_data_stream_1_V_read),
    .standard_plate_data_stream_2_V_dout(standard_plate_data_2_dout),
    .standard_plate_data_stream_2_V_empty_n(standard_plate_data_2_empty_n),
    .standard_plate_data_stream_2_V_read(Loop_BRAM_LOOP_proc7_U0_standard_plate_data_stream_2_V_read),
    .buffer_V_Addr_A(Loop_BRAM_LOOP_proc7_U0_buffer_V_Addr_A),
    .buffer_V_EN_A(Loop_BRAM_LOOP_proc7_U0_buffer_V_EN_A),
    .buffer_V_WEN_A(Loop_BRAM_LOOP_proc7_U0_buffer_V_WEN_A),
    .buffer_V_Din_A(Loop_BRAM_LOOP_proc7_U0_buffer_V_Din_A),
    .buffer_V_Dout_A(32'd0)
);

Add_Rectangle Add_Rectangle_U0(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .ap_start(Add_Rectangle_U0_ap_start),
    .start_full_n(start_for_Mat2AXIvideo_U0_full_n),
    .ap_done(Add_Rectangle_U0_ap_done),
    .ap_continue(Add_Rectangle_U0_ap_continue),
    .ap_idle(Add_Rectangle_U0_ap_idle),
    .ap_ready(Add_Rectangle_U0_ap_ready),
    .start_out(Add_Rectangle_U0_start_out),
    .start_write(Add_Rectangle_U0_start_write),
    .src_data_stream_0_V_dout(copy2_data_stream_0_dout),
    .src_data_stream_0_V_empty_n(copy2_data_stream_0_empty_n),
    .src_data_stream_0_V_read(Add_Rectangle_U0_src_data_stream_0_V_read),
    .src_data_stream_1_V_dout(copy2_data_stream_1_dout),
    .src_data_stream_1_V_empty_n(copy2_data_stream_1_empty_n),
    .src_data_stream_1_V_read(Add_Rectangle_U0_src_data_stream_1_V_read),
    .src_data_stream_2_V_dout(copy2_data_stream_2_dout),
    .src_data_stream_2_V_empty_n(copy2_data_stream_2_empty_n),
    .src_data_stream_2_V_read(Add_Rectangle_U0_src_data_stream_2_V_read),
    .dst_data_stream_0_V_din(Add_Rectangle_U0_dst_data_stream_0_V_din),
    .dst_data_stream_0_V_full_n(output_img_data_stre_full_n),
    .dst_data_stream_0_V_write(Add_Rectangle_U0_dst_data_stream_0_V_write),
    .dst_data_stream_1_V_din(Add_Rectangle_U0_dst_data_stream_1_V_din),
    .dst_data_stream_1_V_full_n(output_img_data_stre_1_full_n),
    .dst_data_stream_1_V_write(Add_Rectangle_U0_dst_data_stream_1_V_write),
    .dst_data_stream_2_V_din(Add_Rectangle_U0_dst_data_stream_2_V_din),
    .dst_data_stream_2_V_full_n(output_img_data_stre_2_full_n),
    .dst_data_stream_2_V_write(Add_Rectangle_U0_dst_data_stream_2_V_write),
    .xleft_dout(xleft_c59_dout),
    .xleft_empty_n(xleft_c59_empty_n),
    .xleft_read(Add_Rectangle_U0_xleft_read),
    .xright_dout(xright_c60_dout),
    .xright_empty_n(xright_c60_empty_n),
    .xright_read(Add_Rectangle_U0_xright_read),
    .ytop_dout(ytop_c61_dout),
    .ytop_empty_n(ytop_c61_empty_n),
    .ytop_read(Add_Rectangle_U0_ytop_read),
    .ydown_dout(ydown_c62_dout),
    .ydown_empty_n(ydown_c62_empty_n),
    .ydown_read(Add_Rectangle_U0_ydown_read)
);

Mat2AXIvideo Mat2AXIvideo_U0(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .ap_start(Mat2AXIvideo_U0_ap_start),
    .ap_done(Mat2AXIvideo_U0_ap_done),
    .ap_continue(Mat2AXIvideo_U0_ap_continue),
    .ap_idle(Mat2AXIvideo_U0_ap_idle),
    .ap_ready(Mat2AXIvideo_U0_ap_ready),
    .img_data_stream_0_V_dout(output_img_data_stre_dout),
    .img_data_stream_0_V_empty_n(output_img_data_stre_empty_n),
    .img_data_stream_0_V_read(Mat2AXIvideo_U0_img_data_stream_0_V_read),
    .img_data_stream_1_V_dout(output_img_data_stre_1_dout),
    .img_data_stream_1_V_empty_n(output_img_data_stre_1_empty_n),
    .img_data_stream_1_V_read(Mat2AXIvideo_U0_img_data_stream_1_V_read),
    .img_data_stream_2_V_dout(output_img_data_stre_2_dout),
    .img_data_stream_2_V_empty_n(output_img_data_stre_2_empty_n),
    .img_data_stream_2_V_read(Mat2AXIvideo_U0_img_data_stream_2_V_read),
    .video_dst_TDATA(Mat2AXIvideo_U0_video_dst_TDATA),
    .video_dst_TVALID(Mat2AXIvideo_U0_video_dst_TVALID),
    .video_dst_TREADY(video_dst_TREADY),
    .video_dst_TKEEP(Mat2AXIvideo_U0_video_dst_TKEEP),
    .video_dst_TSTRB(Mat2AXIvideo_U0_video_dst_TSTRB),
    .video_dst_TUSER(Mat2AXIvideo_U0_video_dst_TUSER),
    .video_dst_TLAST(Mat2AXIvideo_U0_video_dst_TLAST),
    .video_dst_TID(Mat2AXIvideo_U0_video_dst_TID),
    .video_dst_TDEST(Mat2AXIvideo_U0_video_dst_TDEST)
);

fifo_w32_d4_A xleft_c_U(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(Block_Mat_exit48_pro_U0_xleft_out_din),
    .if_full_n(xleft_c_full_n),
    .if_write(Block_Mat_exit48_pro_U0_xleft_out_write),
    .if_dout(xleft_c_dout),
    .if_empty_n(xleft_c_empty_n),
    .if_read(Return_Plate_U0_xleft_read)
);

fifo_w32_d4_A xleft_c59_U(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(Block_Mat_exit48_pro_U0_xleft_out1_din),
    .if_full_n(xleft_c59_full_n),
    .if_write(Block_Mat_exit48_pro_U0_xleft_out1_write),
    .if_dout(xleft_c59_dout),
    .if_empty_n(xleft_c59_empty_n),
    .if_read(Add_Rectangle_U0_xleft_read)
);

fifo_w32_d4_A xright_c_U(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(Block_Mat_exit48_pro_U0_xright_out_din),
    .if_full_n(xright_c_full_n),
    .if_write(Block_Mat_exit48_pro_U0_xright_out_write),
    .if_dout(xright_c_dout),
    .if_empty_n(xright_c_empty_n),
    .if_read(Return_Plate_U0_xright_read)
);

fifo_w32_d4_A xright_c60_U(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(Block_Mat_exit48_pro_U0_xright_out2_din),
    .if_full_n(xright_c60_full_n),
    .if_write(Block_Mat_exit48_pro_U0_xright_out2_write),
    .if_dout(xright_c60_dout),
    .if_empty_n(xright_c60_empty_n),
    .if_read(Add_Rectangle_U0_xright_read)
);

fifo_w32_d4_A ytop_c_U(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(Block_Mat_exit48_pro_U0_ytop_out_din),
    .if_full_n(ytop_c_full_n),
    .if_write(Block_Mat_exit48_pro_U0_ytop_out_write),
    .if_dout(ytop_c_dout),
    .if_empty_n(ytop_c_empty_n),
    .if_read(Return_Plate_U0_ytop_read)
);

fifo_w32_d4_A ytop_c61_U(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(Block_Mat_exit48_pro_U0_ytop_out3_din),
    .if_full_n(ytop_c61_full_n),
    .if_write(Block_Mat_exit48_pro_U0_ytop_out3_write),
    .if_dout(ytop_c61_dout),
    .if_empty_n(ytop_c61_empty_n),
    .if_read(Add_Rectangle_U0_ytop_read)
);

fifo_w32_d4_A ydown_c_U(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(Block_Mat_exit48_pro_U0_ydown_out_din),
    .if_full_n(ydown_c_full_n),
    .if_write(Block_Mat_exit48_pro_U0_ydown_out_write),
    .if_dout(ydown_c_dout),
    .if_empty_n(ydown_c_empty_n),
    .if_read(Return_Plate_U0_ydown_read)
);

fifo_w32_d4_A ydown_c62_U(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(Block_Mat_exit48_pro_U0_ydown_out4_din),
    .if_full_n(ydown_c62_full_n),
    .if_write(Block_Mat_exit48_pro_U0_ydown_out4_write),
    .if_dout(ydown_c62_dout),
    .if_empty_n(ydown_c62_empty_n),
    .if_read(Add_Rectangle_U0_ydown_read)
);

fifo_w11_d2_A rgb_img_rows_V_c_U(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(Block_Mat_exit48_pro_U0_rgb_img_rows_V_out_din),
    .if_full_n(rgb_img_rows_V_c_full_n),
    .if_write(Block_Mat_exit48_pro_U0_rgb_img_rows_V_out_write),
    .if_dout(rgb_img_rows_V_c_dout),
    .if_empty_n(rgb_img_rows_V_c_empty_n),
    .if_read(AXIvideo2Mat_U0_img_rows_V_read)
);

fifo_w12_d2_A rgb_img_cols_V_c_U(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(Block_Mat_exit48_pro_U0_rgb_img_cols_V_out_din),
    .if_full_n(rgb_img_cols_V_c_full_n),
    .if_write(Block_Mat_exit48_pro_U0_rgb_img_cols_V_out_write),
    .if_dout(rgb_img_cols_V_c_dout),
    .if_empty_n(rgb_img_cols_V_c_empty_n),
    .if_read(AXIvideo2Mat_U0_img_cols_V_read)
);

fifo_w32_d5_A plate_rows_V_c_U(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(Block_Mat_exit48_pro_U0_plate_rows_V_out_din),
    .if_full_n(plate_rows_V_c_full_n),
    .if_write(Block_Mat_exit48_pro_U0_plate_rows_V_out_write),
    .if_dout(plate_rows_V_c_dout),
    .if_empty_n(plate_rows_V_c_empty_n),
    .if_read(Resize_U0_p_src_rows_V_read)
);

fifo_w32_d5_A plate_cols_V_c_U(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(Block_Mat_exit48_pro_U0_plate_cols_V_out_din),
    .if_full_n(plate_cols_V_c_full_n),
    .if_write(Block_Mat_exit48_pro_U0_plate_cols_V_out_write),
    .if_dout(plate_cols_V_c_dout),
    .if_empty_n(plate_cols_V_c_empty_n),
    .if_read(Resize_U0_p_src_cols_V_read)
);

fifo_w8_d2_A rgb_img_data_stream_s_U(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(AXIvideo2Mat_U0_img_data_stream_0_V_din),
    .if_full_n(rgb_img_data_stream_s_full_n),
    .if_write(AXIvideo2Mat_U0_img_data_stream_0_V_write),
    .if_dout(rgb_img_data_stream_s_dout),
    .if_empty_n(rgb_img_data_stream_s_empty_n),
    .if_read(Duplicate_U0_src_data_stream_0_V_read)
);

fifo_w8_d2_A rgb_img_data_stream_1_U(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(AXIvideo2Mat_U0_img_data_stream_1_V_din),
    .if_full_n(rgb_img_data_stream_1_full_n),
    .if_write(AXIvideo2Mat_U0_img_data_stream_1_V_write),
    .if_dout(rgb_img_data_stream_1_dout),
    .if_empty_n(rgb_img_data_stream_1_empty_n),
    .if_read(Duplicate_U0_src_data_stream_1_V_read)
);

fifo_w8_d2_A rgb_img_data_stream_2_U(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(AXIvideo2Mat_U0_img_data_stream_2_V_din),
    .if_full_n(rgb_img_data_stream_2_full_n),
    .if_write(AXIvideo2Mat_U0_img_data_stream_2_V_write),
    .if_dout(rgb_img_data_stream_2_dout),
    .if_empty_n(rgb_img_data_stream_2_empty_n),
    .if_read(Duplicate_U0_src_data_stream_2_V_read)
);

fifo_w11_d2_A rgb_img_rows_V_c63_U(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(AXIvideo2Mat_U0_img_rows_V_out_din),
    .if_full_n(rgb_img_rows_V_c63_full_n),
    .if_write(AXIvideo2Mat_U0_img_rows_V_out_write),
    .if_dout(rgb_img_rows_V_c63_dout),
    .if_empty_n(rgb_img_rows_V_c63_empty_n),
    .if_read(Duplicate_U0_src_rows_V_read)
);

fifo_w12_d2_A rgb_img_cols_V_c64_U(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(AXIvideo2Mat_U0_img_cols_V_out_din),
    .if_full_n(rgb_img_cols_V_c64_full_n),
    .if_write(AXIvideo2Mat_U0_img_cols_V_out_write),
    .if_dout(rgb_img_cols_V_c64_dout),
    .if_empty_n(rgb_img_cols_V_c64_empty_n),
    .if_read(Duplicate_U0_src_cols_V_read)
);

fifo_w8_d2_A copy1_data_stream_0_U(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(Duplicate_U0_dst1_data_stream_0_V_din),
    .if_full_n(copy1_data_stream_0_full_n),
    .if_write(Duplicate_U0_dst1_data_stream_0_V_write),
    .if_dout(copy1_data_stream_0_dout),
    .if_empty_n(copy1_data_stream_0_empty_n),
    .if_read(Return_Plate_U0_input_img_data_stream_0_V_read)
);

fifo_w8_d2_A copy1_data_stream_1_U(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(Duplicate_U0_dst1_data_stream_1_V_din),
    .if_full_n(copy1_data_stream_1_full_n),
    .if_write(Duplicate_U0_dst1_data_stream_1_V_write),
    .if_dout(copy1_data_stream_1_dout),
    .if_empty_n(copy1_data_stream_1_empty_n),
    .if_read(Return_Plate_U0_input_img_data_stream_1_V_read)
);

fifo_w8_d2_A copy1_data_stream_2_U(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(Duplicate_U0_dst1_data_stream_2_V_din),
    .if_full_n(copy1_data_stream_2_full_n),
    .if_write(Duplicate_U0_dst1_data_stream_2_V_write),
    .if_dout(copy1_data_stream_2_dout),
    .if_empty_n(copy1_data_stream_2_empty_n),
    .if_read(Return_Plate_U0_input_img_data_stream_2_V_read)
);

fifo_w8_d2_A copy2_data_stream_0_U(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(Duplicate_U0_dst2_data_stream_0_V_din),
    .if_full_n(copy2_data_stream_0_full_n),
    .if_write(Duplicate_U0_dst2_data_stream_0_V_write),
    .if_dout(copy2_data_stream_0_dout),
    .if_empty_n(copy2_data_stream_0_empty_n),
    .if_read(Add_Rectangle_U0_src_data_stream_0_V_read)
);

fifo_w8_d2_A copy2_data_stream_1_U(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(Duplicate_U0_dst2_data_stream_1_V_din),
    .if_full_n(copy2_data_stream_1_full_n),
    .if_write(Duplicate_U0_dst2_data_stream_1_V_write),
    .if_dout(copy2_data_stream_1_dout),
    .if_empty_n(copy2_data_stream_1_empty_n),
    .if_read(Add_Rectangle_U0_src_data_stream_1_V_read)
);

fifo_w8_d2_A copy2_data_stream_2_U(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(Duplicate_U0_dst2_data_stream_2_V_din),
    .if_full_n(copy2_data_stream_2_full_n),
    .if_write(Duplicate_U0_dst2_data_stream_2_V_write),
    .if_dout(copy2_data_stream_2_dout),
    .if_empty_n(copy2_data_stream_2_empty_n),
    .if_read(Add_Rectangle_U0_src_data_stream_2_V_read)
);

fifo_w8_d2_A plate_data_stream_0_U(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(Return_Plate_U0_output_plate_data_stream_0_V_din),
    .if_full_n(plate_data_stream_0_full_n),
    .if_write(Return_Plate_U0_output_plate_data_stream_0_V_write),
    .if_dout(plate_data_stream_0_dout),
    .if_empty_n(plate_data_stream_0_empty_n),
    .if_read(Resize_U0_p_src_data_stream_0_V_read)
);

fifo_w8_d2_A plate_data_stream_1_U(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(Return_Plate_U0_output_plate_data_stream_1_V_din),
    .if_full_n(plate_data_stream_1_full_n),
    .if_write(Return_Plate_U0_output_plate_data_stream_1_V_write),
    .if_dout(plate_data_stream_1_dout),
    .if_empty_n(plate_data_stream_1_empty_n),
    .if_read(Resize_U0_p_src_data_stream_1_V_read)
);

fifo_w8_d2_A plate_data_stream_2_U(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(Return_Plate_U0_output_plate_data_stream_2_V_din),
    .if_full_n(plate_data_stream_2_full_n),
    .if_write(Return_Plate_U0_output_plate_data_stream_2_V_write),
    .if_dout(plate_data_stream_2_dout),
    .if_empty_n(plate_data_stream_2_empty_n),
    .if_read(Resize_U0_p_src_data_stream_2_V_read)
);

fifo_w8_d2_A standard_plate_data_s_U(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(Resize_U0_p_dst_data_stream_0_V_din),
    .if_full_n(standard_plate_data_s_full_n),
    .if_write(Resize_U0_p_dst_data_stream_0_V_write),
    .if_dout(standard_plate_data_s_dout),
    .if_empty_n(standard_plate_data_s_empty_n),
    .if_read(Loop_BRAM_LOOP_proc7_U0_standard_plate_data_stream_0_V_read)
);

fifo_w8_d2_A standard_plate_data_1_U(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(Resize_U0_p_dst_data_stream_1_V_din),
    .if_full_n(standard_plate_data_1_full_n),
    .if_write(Resize_U0_p_dst_data_stream_1_V_write),
    .if_dout(standard_plate_data_1_dout),
    .if_empty_n(standard_plate_data_1_empty_n),
    .if_read(Loop_BRAM_LOOP_proc7_U0_standard_plate_data_stream_1_V_read)
);

fifo_w8_d2_A standard_plate_data_2_U(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(Resize_U0_p_dst_data_stream_2_V_din),
    .if_full_n(standard_plate_data_2_full_n),
    .if_write(Resize_U0_p_dst_data_stream_2_V_write),
    .if_dout(standard_plate_data_2_dout),
    .if_empty_n(standard_plate_data_2_empty_n),
    .if_read(Loop_BRAM_LOOP_proc7_U0_standard_plate_data_stream_2_V_read)
);

fifo_w8_d2_A output_img_data_stre_U(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(Add_Rectangle_U0_dst_data_stream_0_V_din),
    .if_full_n(output_img_data_stre_full_n),
    .if_write(Add_Rectangle_U0_dst_data_stream_0_V_write),
    .if_dout(output_img_data_stre_dout),
    .if_empty_n(output_img_data_stre_empty_n),
    .if_read(Mat2AXIvideo_U0_img_data_stream_0_V_read)
);

fifo_w8_d2_A output_img_data_stre_1_U(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(Add_Rectangle_U0_dst_data_stream_1_V_din),
    .if_full_n(output_img_data_stre_1_full_n),
    .if_write(Add_Rectangle_U0_dst_data_stream_1_V_write),
    .if_dout(output_img_data_stre_1_dout),
    .if_empty_n(output_img_data_stre_1_empty_n),
    .if_read(Mat2AXIvideo_U0_img_data_stream_1_V_read)
);

fifo_w8_d2_A output_img_data_stre_2_U(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(Add_Rectangle_U0_dst_data_stream_2_V_din),
    .if_full_n(output_img_data_stre_2_full_n),
    .if_write(Add_Rectangle_U0_dst_data_stream_2_V_write),
    .if_dout(output_img_data_stre_2_dout),
    .if_empty_n(output_img_data_stre_2_empty_n),
    .if_read(Mat2AXIvideo_U0_img_data_stream_2_V_read)
);

start_for_Return_kbM start_for_Return_kbM_U(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(start_for_Return_Plate_U0_din),
    .if_full_n(start_for_Return_Plate_U0_full_n),
    .if_write(Block_Mat_exit48_pro_U0_start_write),
    .if_dout(start_for_Return_Plate_U0_dout),
    .if_empty_n(start_for_Return_Plate_U0_empty_n),
    .if_read(Return_Plate_U0_ap_ready)
);

start_for_Resize_U0 start_for_Resize_U0_U(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(start_for_Resize_U0_din),
    .if_full_n(start_for_Resize_U0_full_n),
    .if_write(Block_Mat_exit48_pro_U0_start_write),
    .if_dout(start_for_Resize_U0_dout),
    .if_empty_n(start_for_Resize_U0_empty_n),
    .if_read(Resize_U0_ap_ready)
);

start_for_Add_ReclbW start_for_Add_ReclbW_U(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(start_for_Add_Rectangle_U0_din),
    .if_full_n(start_for_Add_Rectangle_U0_full_n),
    .if_write(Block_Mat_exit48_pro_U0_start_write),
    .if_dout(start_for_Add_Rectangle_U0_dout),
    .if_empty_n(start_for_Add_Rectangle_U0_empty_n),
    .if_read(Add_Rectangle_U0_ap_ready)
);

start_for_Duplicamb6 start_for_Duplicamb6_U(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(start_for_Duplicate_U0_din),
    .if_full_n(start_for_Duplicate_U0_full_n),
    .if_write(AXIvideo2Mat_U0_start_write),
    .if_dout(start_for_Duplicate_U0_dout),
    .if_empty_n(start_for_Duplicate_U0_empty_n),
    .if_read(Duplicate_U0_ap_ready)
);

start_for_Loop_BRncg start_for_Loop_BRncg_U(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(start_for_Loop_BRAM_LOOP_proc7_U0_din),
    .if_full_n(start_for_Loop_BRAM_LOOP_proc7_U0_full_n),
    .if_write(Resize_U0_start_write),
    .if_dout(start_for_Loop_BRAM_LOOP_proc7_U0_dout),
    .if_empty_n(start_for_Loop_BRAM_LOOP_proc7_U0_empty_n),
    .if_read(Loop_BRAM_LOOP_proc7_U0_ap_ready)
);

start_for_Mat2AXIocq start_for_Mat2AXIocq_U(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(start_for_Mat2AXIvideo_U0_din),
    .if_full_n(start_for_Mat2AXIvideo_U0_full_n),
    .if_write(Add_Rectangle_U0_start_write),
    .if_dout(start_for_Mat2AXIvideo_U0_dout),
    .if_empty_n(start_for_Mat2AXIvideo_U0_empty_n),
    .if_read(Mat2AXIvideo_U0_ap_ready)
);

always @ (posedge ap_clk) begin
    if (ap_rst_n_inv == 1'b1) begin
        ap_sync_reg_AXIvideo2Mat_U0_ap_ready <= 1'b0;
    end else begin
        if (((ap_sync_ready & ap_start) == 1'b1)) begin
            ap_sync_reg_AXIvideo2Mat_U0_ap_ready <= 1'b0;
        end else begin
            ap_sync_reg_AXIvideo2Mat_U0_ap_ready <= ap_sync_AXIvideo2Mat_U0_ap_ready;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst_n_inv == 1'b1) begin
        ap_sync_reg_Block_Mat_exit48_pro_U0_ap_ready <= 1'b0;
    end else begin
        if (((ap_sync_ready & ap_start) == 1'b1)) begin
            ap_sync_reg_Block_Mat_exit48_pro_U0_ap_ready <= 1'b0;
        end else begin
            ap_sync_reg_Block_Mat_exit48_pro_U0_ap_ready <= ap_sync_Block_Mat_exit48_pro_U0_ap_ready;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == AXIvideo2Mat_U0_ap_ready) & (ap_sync_ready == 1'b1))) begin
        AXIvideo2Mat_U0_ap_ready_count <= (AXIvideo2Mat_U0_ap_ready_count - 2'd1);
    end else if (((ap_sync_ready == 1'b0) & (1'b1 == AXIvideo2Mat_U0_ap_ready))) begin
        AXIvideo2Mat_U0_ap_ready_count <= (AXIvideo2Mat_U0_ap_ready_count + 2'd1);
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == Block_Mat_exit48_pro_U0_ap_ready) & (ap_sync_ready == 1'b1))) begin
        Block_Mat_exit48_pro_U0_ap_ready_count <= (Block_Mat_exit48_pro_U0_ap_ready_count - 2'd1);
    end else if (((ap_sync_ready == 1'b0) & (1'b1 == Block_Mat_exit48_pro_U0_ap_ready))) begin
        Block_Mat_exit48_pro_U0_ap_ready_count <= (Block_Mat_exit48_pro_U0_ap_ready_count + 2'd1);
    end
end

assign AXIvideo2Mat_U0_ap_continue = 1'b1;

assign AXIvideo2Mat_U0_ap_start = ((ap_sync_reg_AXIvideo2Mat_U0_ap_ready ^ 1'b1) & ap_start);

assign Add_Rectangle_U0_ap_continue = 1'b1;

assign Add_Rectangle_U0_ap_start = start_for_Add_Rectangle_U0_empty_n;

assign Block_Mat_exit48_pro_U0_ap_continue = 1'b1;

assign Block_Mat_exit48_pro_U0_ap_start = ((ap_sync_reg_Block_Mat_exit48_pro_U0_ap_ready ^ 1'b1) & ap_start);

assign Block_Mat_exit48_pro_U0_start_full_n = (start_for_Return_Plate_U0_full_n & start_for_Resize_U0_full_n & start_for_Add_Rectangle_U0_full_n);

assign Duplicate_U0_ap_continue = 1'b1;

assign Duplicate_U0_ap_start = start_for_Duplicate_U0_empty_n;

assign Duplicate_U0_start_full_n = 1'b1;

assign Duplicate_U0_start_write = 1'b0;

assign Loop_BRAM_LOOP_proc7_U0_ap_continue = ap_sync_done;

assign Loop_BRAM_LOOP_proc7_U0_ap_start = start_for_Loop_BRAM_LOOP_proc7_U0_empty_n;

assign Loop_BRAM_LOOP_proc7_U0_start_full_n = 1'b1;

assign Loop_BRAM_LOOP_proc7_U0_start_write = 1'b0;

assign Mat2AXIvideo_U0_ap_continue = ap_sync_done;

assign Mat2AXIvideo_U0_ap_start = start_for_Mat2AXIvideo_U0_empty_n;

assign Mat2AXIvideo_U0_start_full_n = 1'b1;

assign Mat2AXIvideo_U0_start_write = 1'b0;

assign Resize_U0_ap_continue = 1'b1;

assign Resize_U0_ap_start = start_for_Resize_U0_empty_n;

assign Return_Plate_U0_ap_continue = 1'b1;

assign Return_Plate_U0_ap_start = start_for_Return_Plate_U0_empty_n;

assign Return_Plate_U0_start_full_n = 1'b1;

assign Return_Plate_U0_start_write = 1'b0;

assign ap_done = ap_sync_done;

assign ap_idle = (Return_Plate_U0_ap_idle & Resize_U0_ap_idle & Mat2AXIvideo_U0_ap_idle & Loop_BRAM_LOOP_proc7_U0_ap_idle & Duplicate_U0_ap_idle & Block_Mat_exit48_pro_U0_ap_idle & Add_Rectangle_U0_ap_idle & AXIvideo2Mat_U0_ap_idle);

assign ap_ready = ap_sync_ready;

always @ (*) begin
    ap_rst_n_inv = ~ap_rst_n;
end

assign ap_sync_AXIvideo2Mat_U0_ap_ready = (ap_sync_reg_AXIvideo2Mat_U0_ap_ready | AXIvideo2Mat_U0_ap_ready);

assign ap_sync_Block_Mat_exit48_pro_U0_ap_ready = (ap_sync_reg_Block_Mat_exit48_pro_U0_ap_ready | Block_Mat_exit48_pro_U0_ap_ready);

assign ap_sync_continue = ap_sync_done;

assign ap_sync_done = (Mat2AXIvideo_U0_ap_done & Loop_BRAM_LOOP_proc7_U0_ap_done);

assign ap_sync_ready = (ap_sync_Block_Mat_exit48_pro_U0_ap_ready & ap_sync_AXIvideo2Mat_U0_ap_ready);

assign buffer_V_Addr_A = Loop_BRAM_LOOP_proc7_U0_buffer_V_Addr_A;

assign buffer_V_Addr_B = 32'd0;

assign buffer_V_Clk_A = ap_clk;

assign buffer_V_Clk_B = ap_clk;

assign buffer_V_Din_A = Loop_BRAM_LOOP_proc7_U0_buffer_V_Din_A;

assign buffer_V_Din_B = 32'd0;

assign buffer_V_EN_A = Loop_BRAM_LOOP_proc7_U0_buffer_V_EN_A;

assign buffer_V_EN_B = 1'b0;

assign buffer_V_Rst_A = ap_rst_n_inv;

assign buffer_V_Rst_B = ap_rst_n_inv;

assign buffer_V_WEN_A = Loop_BRAM_LOOP_proc7_U0_buffer_V_WEN_A;

assign buffer_V_WEN_B = 1'b0;

assign start_for_Add_Rectangle_U0_din = 1'b1;

assign start_for_Duplicate_U0_din = 1'b1;

assign start_for_Loop_BRAM_LOOP_proc7_U0_din = 1'b1;

assign start_for_Mat2AXIvideo_U0_din = 1'b1;

assign start_for_Resize_U0_din = 1'b1;

assign start_for_Return_Plate_U0_din = 1'b1;

assign video_dst_TDATA = Mat2AXIvideo_U0_video_dst_TDATA;

assign video_dst_TDEST = Mat2AXIvideo_U0_video_dst_TDEST;

assign video_dst_TID = Mat2AXIvideo_U0_video_dst_TID;

assign video_dst_TKEEP = Mat2AXIvideo_U0_video_dst_TKEEP;

assign video_dst_TLAST = Mat2AXIvideo_U0_video_dst_TLAST;

assign video_dst_TSTRB = Mat2AXIvideo_U0_video_dst_TSTRB;

assign video_dst_TUSER = Mat2AXIvideo_U0_video_dst_TUSER;

assign video_dst_TVALID = Mat2AXIvideo_U0_video_dst_TVALID;

assign video_src_TREADY = AXIvideo2Mat_U0_video_src_TREADY;

endmodule //box
