-- ==============================================================
-- RTL generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and OpenCL
-- Version: 2019.2
-- Copyright (C) 1986-2019 Xilinx, Inc. All Rights Reserved.
-- 
-- ===========================================================

library IEEE;
use IEEE.std_logic_1164.all;
use IEEE.numeric_std.all;

entity AXIvideo2Mat is
port (
    ap_clk : IN STD_LOGIC;
    ap_rst : IN STD_LOGIC;
    ap_start : IN STD_LOGIC;
    start_full_n : IN STD_LOGIC;
    ap_done : OUT STD_LOGIC;
    ap_continue : IN STD_LOGIC;
    ap_idle : OUT STD_LOGIC;
    ap_ready : OUT STD_LOGIC;
    start_out : OUT STD_LOGIC;
    start_write : OUT STD_LOGIC;
    video_src_TDATA : IN STD_LOGIC_VECTOR (31 downto 0);
    video_src_TVALID : IN STD_LOGIC;
    video_src_TREADY : OUT STD_LOGIC;
    video_src_TKEEP : IN STD_LOGIC_VECTOR (3 downto 0);
    video_src_TSTRB : IN STD_LOGIC_VECTOR (3 downto 0);
    video_src_TUSER : IN STD_LOGIC_VECTOR (0 downto 0);
    video_src_TLAST : IN STD_LOGIC_VECTOR (0 downto 0);
    video_src_TID : IN STD_LOGIC_VECTOR (0 downto 0);
    video_src_TDEST : IN STD_LOGIC_VECTOR (0 downto 0);
    img_rows_V_dout : IN STD_LOGIC_VECTOR (10 downto 0);
    img_rows_V_empty_n : IN STD_LOGIC;
    img_rows_V_read : OUT STD_LOGIC;
    img_cols_V_dout : IN STD_LOGIC_VECTOR (11 downto 0);
    img_cols_V_empty_n : IN STD_LOGIC;
    img_cols_V_read : OUT STD_LOGIC;
    img_data_stream_0_V_din : OUT STD_LOGIC_VECTOR (7 downto 0);
    img_data_stream_0_V_full_n : IN STD_LOGIC;
    img_data_stream_0_V_write : OUT STD_LOGIC;
    img_data_stream_1_V_din : OUT STD_LOGIC_VECTOR (7 downto 0);
    img_data_stream_1_V_full_n : IN STD_LOGIC;
    img_data_stream_1_V_write : OUT STD_LOGIC;
    img_data_stream_2_V_din : OUT STD_LOGIC_VECTOR (7 downto 0);
    img_data_stream_2_V_full_n : IN STD_LOGIC;
    img_data_stream_2_V_write : OUT STD_LOGIC;
    img_rows_V_out_din : OUT STD_LOGIC_VECTOR (10 downto 0);
    img_rows_V_out_full_n : IN STD_LOGIC;
    img_rows_V_out_write : OUT STD_LOGIC;
    img_cols_V_out_din : OUT STD_LOGIC_VECTOR (11 downto 0);
    img_cols_V_out_full_n : IN STD_LOGIC;
    img_cols_V_out_write : OUT STD_LOGIC );
end;


architecture behav of AXIvideo2Mat is 
    constant ap_const_logic_1 : STD_LOGIC := '1';
    constant ap_const_logic_0 : STD_LOGIC := '0';
    constant ap_ST_fsm_state1 : STD_LOGIC_VECTOR (7 downto 0) := "00000001";
    constant ap_ST_fsm_state2 : STD_LOGIC_VECTOR (7 downto 0) := "00000010";
    constant ap_ST_fsm_state3 : STD_LOGIC_VECTOR (7 downto 0) := "00000100";
    constant ap_ST_fsm_state4 : STD_LOGIC_VECTOR (7 downto 0) := "00001000";
    constant ap_ST_fsm_pp1_stage0 : STD_LOGIC_VECTOR (7 downto 0) := "00010000";
    constant ap_ST_fsm_state7 : STD_LOGIC_VECTOR (7 downto 0) := "00100000";
    constant ap_ST_fsm_state8 : STD_LOGIC_VECTOR (7 downto 0) := "01000000";
    constant ap_ST_fsm_state9 : STD_LOGIC_VECTOR (7 downto 0) := "10000000";
    constant ap_const_boolean_1 : BOOLEAN := true;
    constant ap_const_lv32_0 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000000";
    constant ap_const_lv32_1 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000001";
    constant ap_const_lv32_4 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000100";
    constant ap_const_boolean_0 : BOOLEAN := false;
    constant ap_const_lv1_0 : STD_LOGIC_VECTOR (0 downto 0) := "0";
    constant ap_const_lv32_6 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000110";
    constant ap_const_lv32_3 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000011";
    constant ap_const_lv1_1 : STD_LOGIC_VECTOR (0 downto 0) := "1";
    constant ap_const_lv32_7 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000111";
    constant ap_const_lv32_2 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000010";
    constant ap_const_lv32_5 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000101";
    constant ap_const_lv32_8 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000001000";
    constant ap_const_lv32_F : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000001111";
    constant ap_const_lv32_10 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000010000";
    constant ap_const_lv32_17 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000010111";

    signal real_start : STD_LOGIC;
    signal start_once_reg : STD_LOGIC := '0';
    signal ap_done_reg : STD_LOGIC := '0';
    signal ap_CS_fsm : STD_LOGIC_VECTOR (7 downto 0) := "00000001";
    attribute fsm_encoding : string;
    attribute fsm_encoding of ap_CS_fsm : signal is "none";
    signal ap_CS_fsm_state1 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state1 : signal is "none";
    signal internal_ap_ready : STD_LOGIC;
    signal video_src_TDATA_blk_n : STD_LOGIC;
    signal ap_CS_fsm_state2 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state2 : signal is "none";
    signal ap_CS_fsm_pp1_stage0 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_pp1_stage0 : signal is "none";
    signal ap_enable_reg_pp1_iter0 : STD_LOGIC := '0';
    signal ap_block_pp1_stage0 : BOOLEAN;
    signal icmp_ln73_fu_420_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal or_ln76_fu_434_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_CS_fsm_state8 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state8 : signal is "none";
    signal ap_phi_mux_eol_2_i_phi_fu_375_p4 : STD_LOGIC_VECTOR (0 downto 0);
    signal img_rows_V_blk_n : STD_LOGIC;
    signal img_cols_V_blk_n : STD_LOGIC;
    signal img_data_stream_0_V_blk_n : STD_LOGIC;
    signal ap_enable_reg_pp1_iter1 : STD_LOGIC := '0';
    signal icmp_ln73_reg_508 : STD_LOGIC_VECTOR (0 downto 0);
    signal img_data_stream_1_V_blk_n : STD_LOGIC;
    signal img_data_stream_2_V_blk_n : STD_LOGIC;
    signal img_rows_V_out_blk_n : STD_LOGIC;
    signal img_cols_V_out_blk_n : STD_LOGIC;
    signal eol_reg_278 : STD_LOGIC_VECTOR (0 downto 0);
    signal axi_data_V_1_i_reg_289 : STD_LOGIC_VECTOR (31 downto 0);
    signal t_V_12_reg_300 : STD_LOGIC_VECTOR (31 downto 0);
    signal eol_0_i_reg_311 : STD_LOGIC_VECTOR (0 downto 0);
    signal axi_last_V_2_i_reg_323 : STD_LOGIC_VECTOR (0 downto 0);
    signal p_Val2_s_reg_336 : STD_LOGIC_VECTOR (31 downto 0);
    signal rows_V_fu_392_p1 : STD_LOGIC_VECTOR (31 downto 0);
    signal rows_V_reg_469 : STD_LOGIC_VECTOR (31 downto 0);
    signal ap_block_state1 : BOOLEAN;
    signal cols_V_fu_396_p1 : STD_LOGIC_VECTOR (31 downto 0);
    signal cols_V_reg_474 : STD_LOGIC_VECTOR (31 downto 0);
    signal tmp_data_V_reg_479 : STD_LOGIC_VECTOR (31 downto 0);
    signal tmp_last_V_reg_487 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln71_fu_409_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_CS_fsm_state4 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state4 : signal is "none";
    signal i_V_fu_414_p2 : STD_LOGIC_VECTOR (31 downto 0);
    signal i_V_reg_503 : STD_LOGIC_VECTOR (31 downto 0);
    signal ap_predicate_op67_read_state5 : BOOLEAN;
    signal ap_block_state5_pp1_stage0_iter0 : BOOLEAN;
    signal ap_block_state6_pp1_stage0_iter1 : BOOLEAN;
    signal ap_block_pp1_stage0_11001 : BOOLEAN;
    signal j_V_fu_425_p2 : STD_LOGIC_VECTOR (31 downto 0);
    signal tmp_fu_440_p1 : STD_LOGIC_VECTOR (7 downto 0);
    signal tmp_reg_521 : STD_LOGIC_VECTOR (7 downto 0);
    signal tmp_31_reg_526 : STD_LOGIC_VECTOR (7 downto 0);
    signal tmp_32_reg_531 : STD_LOGIC_VECTOR (7 downto 0);
    signal ap_block_state8 : BOOLEAN;
    signal ap_block_pp1_stage0_subdone : BOOLEAN;
    signal ap_condition_pp1_exit_iter0_state5 : STD_LOGIC;
    signal axi_last_V_3_i_reg_348 : STD_LOGIC_VECTOR (0 downto 0);
    signal axi_last_V_0_i_reg_247 : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_CS_fsm_state9 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state9 : signal is "none";
    signal ap_CS_fsm_state3 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state3 : signal is "none";
    signal axi_data_V_3_i_reg_360 : STD_LOGIC_VECTOR (31 downto 0);
    signal axi_data_V_0_i_reg_257 : STD_LOGIC_VECTOR (31 downto 0);
    signal t_V_reg_267 : STD_LOGIC_VECTOR (31 downto 0);
    signal ap_phi_mux_eol_phi_fu_281_p4 : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_phi_mux_axi_data_V_1_i_phi_fu_292_p4 : STD_LOGIC_VECTOR (31 downto 0);
    signal ap_phi_mux_eol_0_i_phi_fu_315_p4 : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_phi_reg_pp1_iter0_axi_last_V_2_i_reg_323 : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_phi_mux_p_Val2_s_phi_fu_340_p4 : STD_LOGIC_VECTOR (31 downto 0);
    signal ap_phi_reg_pp1_iter0_p_Val2_s_reg_336 : STD_LOGIC_VECTOR (31 downto 0);
    signal ap_CS_fsm_state7 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state7 : signal is "none";
    signal eol_2_i_reg_372 : STD_LOGIC_VECTOR (0 downto 0);
    signal sof_1_i_fu_176 : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_block_pp1_stage0_01001 : BOOLEAN;
    signal rows_V_fu_392_p0 : STD_LOGIC_VECTOR (10 downto 0);
    signal cols_V_fu_396_p0 : STD_LOGIC_VECTOR (11 downto 0);
    signal tmp_user_V_fu_400_p1 : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_NS_fsm : STD_LOGIC_VECTOR (7 downto 0);
    signal ap_idle_pp1 : STD_LOGIC;
    signal ap_enable_pp1 : STD_LOGIC;
    signal regslice_both_AXI_video_strm_V_data_V_U_apdone_blk : STD_LOGIC;
    signal video_src_TDATA_int : STD_LOGIC_VECTOR (31 downto 0);
    signal video_src_TVALID_int : STD_LOGIC;
    signal video_src_TREADY_int : STD_LOGIC;
    signal regslice_both_AXI_video_strm_V_data_V_U_ack_in : STD_LOGIC;
    signal regslice_both_AXI_video_strm_V_keep_V_U_apdone_blk : STD_LOGIC;
    signal video_src_TKEEP_int : STD_LOGIC_VECTOR (3 downto 0);
    signal regslice_both_AXI_video_strm_V_keep_V_U_vld_out : STD_LOGIC;
    signal regslice_both_AXI_video_strm_V_keep_V_U_ack_in : STD_LOGIC;
    signal regslice_both_AXI_video_strm_V_strb_V_U_apdone_blk : STD_LOGIC;
    signal video_src_TSTRB_int : STD_LOGIC_VECTOR (3 downto 0);
    signal regslice_both_AXI_video_strm_V_strb_V_U_vld_out : STD_LOGIC;
    signal regslice_both_AXI_video_strm_V_strb_V_U_ack_in : STD_LOGIC;
    signal regslice_both_AXI_video_strm_V_user_V_U_apdone_blk : STD_LOGIC;
    signal video_src_TUSER_int : STD_LOGIC_VECTOR (0 downto 0);
    signal regslice_both_AXI_video_strm_V_user_V_U_vld_out : STD_LOGIC;
    signal regslice_both_AXI_video_strm_V_user_V_U_ack_in : STD_LOGIC;
    signal regslice_both_AXI_video_strm_V_last_V_U_apdone_blk : STD_LOGIC;
    signal video_src_TLAST_int : STD_LOGIC_VECTOR (0 downto 0);
    signal regslice_both_AXI_video_strm_V_last_V_U_vld_out : STD_LOGIC;
    signal regslice_both_AXI_video_strm_V_last_V_U_ack_in : STD_LOGIC;
    signal regslice_both_AXI_video_strm_V_id_V_U_apdone_blk : STD_LOGIC;
    signal video_src_TID_int : STD_LOGIC_VECTOR (0 downto 0);
    signal regslice_both_AXI_video_strm_V_id_V_U_vld_out : STD_LOGIC;
    signal regslice_both_AXI_video_strm_V_id_V_U_ack_in : STD_LOGIC;
    signal regslice_both_AXI_video_strm_V_dest_V_U_apdone_blk : STD_LOGIC;
    signal video_src_TDEST_int : STD_LOGIC_VECTOR (0 downto 0);
    signal regslice_both_AXI_video_strm_V_dest_V_U_vld_out : STD_LOGIC;
    signal regslice_both_AXI_video_strm_V_dest_V_U_ack_in : STD_LOGIC;
    signal ap_condition_200 : BOOLEAN;

    component regslice_both IS
    generic (
        DataWidth : INTEGER );
    port (
        ap_clk : IN STD_LOGIC;
        ap_rst : IN STD_LOGIC;
        data_in : IN STD_LOGIC_VECTOR (DataWidth-1 downto 0);
        vld_in : IN STD_LOGIC;
        ack_in : OUT STD_LOGIC;
        data_out : OUT STD_LOGIC_VECTOR (DataWidth-1 downto 0);
        vld_out : OUT STD_LOGIC;
        ack_out : IN STD_LOGIC;
        apdone_blk : OUT STD_LOGIC );
    end component;



begin
    regslice_both_AXI_video_strm_V_data_V_U : component regslice_both
    generic map (
        DataWidth => 32)
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst,
        data_in => video_src_TDATA,
        vld_in => video_src_TVALID,
        ack_in => regslice_both_AXI_video_strm_V_data_V_U_ack_in,
        data_out => video_src_TDATA_int,
        vld_out => video_src_TVALID_int,
        ack_out => video_src_TREADY_int,
        apdone_blk => regslice_both_AXI_video_strm_V_data_V_U_apdone_blk);

    regslice_both_AXI_video_strm_V_keep_V_U : component regslice_both
    generic map (
        DataWidth => 4)
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst,
        data_in => video_src_TKEEP,
        vld_in => video_src_TVALID,
        ack_in => regslice_both_AXI_video_strm_V_keep_V_U_ack_in,
        data_out => video_src_TKEEP_int,
        vld_out => regslice_both_AXI_video_strm_V_keep_V_U_vld_out,
        ack_out => video_src_TREADY_int,
        apdone_blk => regslice_both_AXI_video_strm_V_keep_V_U_apdone_blk);

    regslice_both_AXI_video_strm_V_strb_V_U : component regslice_both
    generic map (
        DataWidth => 4)
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst,
        data_in => video_src_TSTRB,
        vld_in => video_src_TVALID,
        ack_in => regslice_both_AXI_video_strm_V_strb_V_U_ack_in,
        data_out => video_src_TSTRB_int,
        vld_out => regslice_both_AXI_video_strm_V_strb_V_U_vld_out,
        ack_out => video_src_TREADY_int,
        apdone_blk => regslice_both_AXI_video_strm_V_strb_V_U_apdone_blk);

    regslice_both_AXI_video_strm_V_user_V_U : component regslice_both
    generic map (
        DataWidth => 1)
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst,
        data_in => video_src_TUSER,
        vld_in => video_src_TVALID,
        ack_in => regslice_both_AXI_video_strm_V_user_V_U_ack_in,
        data_out => video_src_TUSER_int,
        vld_out => regslice_both_AXI_video_strm_V_user_V_U_vld_out,
        ack_out => video_src_TREADY_int,
        apdone_blk => regslice_both_AXI_video_strm_V_user_V_U_apdone_blk);

    regslice_both_AXI_video_strm_V_last_V_U : component regslice_both
    generic map (
        DataWidth => 1)
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst,
        data_in => video_src_TLAST,
        vld_in => video_src_TVALID,
        ack_in => regslice_both_AXI_video_strm_V_last_V_U_ack_in,
        data_out => video_src_TLAST_int,
        vld_out => regslice_both_AXI_video_strm_V_last_V_U_vld_out,
        ack_out => video_src_TREADY_int,
        apdone_blk => regslice_both_AXI_video_strm_V_last_V_U_apdone_blk);

    regslice_both_AXI_video_strm_V_id_V_U : component regslice_both
    generic map (
        DataWidth => 1)
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst,
        data_in => video_src_TID,
        vld_in => video_src_TVALID,
        ack_in => regslice_both_AXI_video_strm_V_id_V_U_ack_in,
        data_out => video_src_TID_int,
        vld_out => regslice_both_AXI_video_strm_V_id_V_U_vld_out,
        ack_out => video_src_TREADY_int,
        apdone_blk => regslice_both_AXI_video_strm_V_id_V_U_apdone_blk);

    regslice_both_AXI_video_strm_V_dest_V_U : component regslice_both
    generic map (
        DataWidth => 1)
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst,
        data_in => video_src_TDEST,
        vld_in => video_src_TVALID,
        ack_in => regslice_both_AXI_video_strm_V_dest_V_U_ack_in,
        data_out => video_src_TDEST_int,
        vld_out => regslice_both_AXI_video_strm_V_dest_V_U_vld_out,
        ack_out => video_src_TREADY_int,
        apdone_blk => regslice_both_AXI_video_strm_V_dest_V_U_apdone_blk);





    ap_CS_fsm_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_CS_fsm <= ap_ST_fsm_state1;
            else
                ap_CS_fsm <= ap_NS_fsm;
            end if;
        end if;
    end process;


    ap_done_reg_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_done_reg <= ap_const_logic_0;
            else
                if ((ap_continue = ap_const_logic_1)) then 
                    ap_done_reg <= ap_const_logic_0;
                elsif (((ap_const_logic_1 = ap_CS_fsm_state4) and (icmp_ln71_fu_409_p2 = ap_const_lv1_1))) then 
                    ap_done_reg <= ap_const_logic_1;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp1_iter0_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp1_iter0 <= ap_const_logic_0;
            else
                if (((ap_const_boolean_0 = ap_block_pp1_stage0_subdone) and (ap_const_logic_1 = ap_CS_fsm_pp1_stage0) and (ap_const_logic_1 = ap_condition_pp1_exit_iter0_state5))) then 
                    ap_enable_reg_pp1_iter0 <= ap_const_logic_0;
                elsif (((ap_const_logic_1 = ap_CS_fsm_state4) and (icmp_ln71_fu_409_p2 = ap_const_lv1_0))) then 
                    ap_enable_reg_pp1_iter0 <= ap_const_logic_1;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp1_iter1_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp1_iter1 <= ap_const_logic_0;
            else
                if (((ap_const_boolean_0 = ap_block_pp1_stage0_subdone) and (ap_const_logic_1 = ap_condition_pp1_exit_iter0_state5))) then 
                    ap_enable_reg_pp1_iter1 <= (ap_const_logic_1 xor ap_condition_pp1_exit_iter0_state5);
                elsif ((ap_const_boolean_0 = ap_block_pp1_stage0_subdone)) then 
                    ap_enable_reg_pp1_iter1 <= ap_enable_reg_pp1_iter0;
                elsif (((ap_const_logic_1 = ap_CS_fsm_state4) and (icmp_ln71_fu_409_p2 = ap_const_lv1_0))) then 
                    ap_enable_reg_pp1_iter1 <= ap_const_logic_0;
                end if; 
            end if;
        end if;
    end process;


    start_once_reg_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                start_once_reg <= ap_const_logic_0;
            else
                if (((internal_ap_ready = ap_const_logic_0) and (real_start = ap_const_logic_1))) then 
                    start_once_reg <= ap_const_logic_1;
                elsif ((internal_ap_ready = ap_const_logic_1)) then 
                    start_once_reg <= ap_const_logic_0;
                end if; 
            end if;
        end if;
    end process;


    axi_data_V_0_i_reg_257_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_logic_1 = ap_CS_fsm_state3)) then 
                axi_data_V_0_i_reg_257 <= tmp_data_V_reg_479;
            elsif ((ap_const_logic_1 = ap_CS_fsm_state9)) then 
                axi_data_V_0_i_reg_257 <= axi_data_V_3_i_reg_360;
            end if; 
        end if;
    end process;

    axi_data_V_1_i_reg_289_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_logic_1 = ap_CS_fsm_pp1_stage0) and (ap_enable_reg_pp1_iter1 = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp1_stage0_11001) and (icmp_ln73_reg_508 = ap_const_lv1_0))) then 
                axi_data_V_1_i_reg_289 <= p_Val2_s_reg_336;
            elsif (((ap_const_logic_1 = ap_CS_fsm_state4) and (icmp_ln71_fu_409_p2 = ap_const_lv1_0))) then 
                axi_data_V_1_i_reg_289 <= axi_data_V_0_i_reg_257;
            end if; 
        end if;
    end process;

    axi_data_V_3_i_reg_360_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_logic_1 = ap_CS_fsm_state7)) then 
                axi_data_V_3_i_reg_360 <= axi_data_V_1_i_reg_289;
            elsif ((not(((video_src_TVALID_int = ap_const_logic_0) and (eol_2_i_reg_372 = ap_const_lv1_0))) and (ap_const_logic_1 = ap_CS_fsm_state8) and (eol_2_i_reg_372 = ap_const_lv1_0))) then 
                axi_data_V_3_i_reg_360 <= video_src_TDATA_int;
            end if; 
        end if;
    end process;

    axi_last_V_0_i_reg_247_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_logic_1 = ap_CS_fsm_state3)) then 
                axi_last_V_0_i_reg_247 <= tmp_last_V_reg_487;
            elsif ((ap_const_logic_1 = ap_CS_fsm_state9)) then 
                axi_last_V_0_i_reg_247 <= axi_last_V_3_i_reg_348;
            end if; 
        end if;
    end process;

    axi_last_V_2_i_reg_323_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_boolean_1 = ap_condition_200)) then
                if (((or_ln76_fu_434_p2 = ap_const_lv1_1) and (icmp_ln73_fu_420_p2 = ap_const_lv1_0))) then 
                    axi_last_V_2_i_reg_323 <= ap_phi_mux_eol_phi_fu_281_p4;
                elsif (((or_ln76_fu_434_p2 = ap_const_lv1_0) and (icmp_ln73_fu_420_p2 = ap_const_lv1_0))) then 
                    axi_last_V_2_i_reg_323 <= video_src_TLAST_int;
                elsif ((ap_const_boolean_1 = ap_const_boolean_1)) then 
                    axi_last_V_2_i_reg_323 <= ap_phi_reg_pp1_iter0_axi_last_V_2_i_reg_323;
                end if;
            end if; 
        end if;
    end process;

    axi_last_V_3_i_reg_348_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_logic_1 = ap_CS_fsm_state7)) then 
                axi_last_V_3_i_reg_348 <= eol_reg_278;
            elsif ((not(((video_src_TVALID_int = ap_const_logic_0) and (eol_2_i_reg_372 = ap_const_lv1_0))) and (ap_const_logic_1 = ap_CS_fsm_state8) and (eol_2_i_reg_372 = ap_const_lv1_0))) then 
                axi_last_V_3_i_reg_348 <= video_src_TLAST_int;
            end if; 
        end if;
    end process;

    eol_0_i_reg_311_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_logic_1 = ap_CS_fsm_pp1_stage0) and (ap_enable_reg_pp1_iter1 = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp1_stage0_11001) and (icmp_ln73_reg_508 = ap_const_lv1_0))) then 
                eol_0_i_reg_311 <= axi_last_V_2_i_reg_323;
            elsif (((ap_const_logic_1 = ap_CS_fsm_state4) and (icmp_ln71_fu_409_p2 = ap_const_lv1_0))) then 
                eol_0_i_reg_311 <= ap_const_lv1_0;
            end if; 
        end if;
    end process;

    eol_2_i_reg_372_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_logic_1 = ap_CS_fsm_state7)) then 
                eol_2_i_reg_372 <= eol_0_i_reg_311;
            elsif ((not(((video_src_TVALID_int = ap_const_logic_0) and (eol_2_i_reg_372 = ap_const_lv1_0))) and (ap_const_logic_1 = ap_CS_fsm_state8) and (eol_2_i_reg_372 = ap_const_lv1_0))) then 
                eol_2_i_reg_372 <= video_src_TLAST_int;
            end if; 
        end if;
    end process;

    eol_reg_278_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_logic_1 = ap_CS_fsm_pp1_stage0) and (ap_enable_reg_pp1_iter1 = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp1_stage0_11001) and (icmp_ln73_reg_508 = ap_const_lv1_0))) then 
                eol_reg_278 <= axi_last_V_2_i_reg_323;
            elsif (((ap_const_logic_1 = ap_CS_fsm_state4) and (icmp_ln71_fu_409_p2 = ap_const_lv1_0))) then 
                eol_reg_278 <= axi_last_V_0_i_reg_247;
            end if; 
        end if;
    end process;

    p_Val2_s_reg_336_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_boolean_1 = ap_condition_200)) then
                if (((or_ln76_fu_434_p2 = ap_const_lv1_1) and (icmp_ln73_fu_420_p2 = ap_const_lv1_0))) then 
                    p_Val2_s_reg_336 <= ap_phi_mux_axi_data_V_1_i_phi_fu_292_p4;
                elsif (((or_ln76_fu_434_p2 = ap_const_lv1_0) and (icmp_ln73_fu_420_p2 = ap_const_lv1_0))) then 
                    p_Val2_s_reg_336 <= video_src_TDATA_int;
                elsif ((ap_const_boolean_1 = ap_const_boolean_1)) then 
                    p_Val2_s_reg_336 <= ap_phi_reg_pp1_iter0_p_Val2_s_reg_336;
                end if;
            end if; 
        end if;
    end process;

    sof_1_i_fu_176_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_enable_reg_pp1_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp1_stage0) and (ap_const_boolean_0 = ap_block_pp1_stage0_11001) and (icmp_ln73_fu_420_p2 = ap_const_lv1_0))) then 
                sof_1_i_fu_176 <= ap_const_lv1_0;
            elsif ((ap_const_logic_1 = ap_CS_fsm_state3)) then 
                sof_1_i_fu_176 <= ap_const_lv1_1;
            end if; 
        end if;
    end process;

    t_V_12_reg_300_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_enable_reg_pp1_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp1_stage0) and (ap_const_boolean_0 = ap_block_pp1_stage0_11001) and (icmp_ln73_fu_420_p2 = ap_const_lv1_0))) then 
                t_V_12_reg_300 <= j_V_fu_425_p2;
            elsif (((ap_const_logic_1 = ap_CS_fsm_state4) and (icmp_ln71_fu_409_p2 = ap_const_lv1_0))) then 
                t_V_12_reg_300 <= ap_const_lv32_0;
            end if; 
        end if;
    end process;

    t_V_reg_267_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_logic_1 = ap_CS_fsm_state3)) then 
                t_V_reg_267 <= ap_const_lv32_0;
            elsif ((ap_const_logic_1 = ap_CS_fsm_state9)) then 
                t_V_reg_267 <= i_V_reg_503;
            end if; 
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((not(((img_cols_V_out_full_n = ap_const_logic_0) or (img_rows_V_out_full_n = ap_const_logic_0) or (img_cols_V_empty_n = ap_const_logic_0) or (img_rows_V_empty_n = ap_const_logic_0) or (real_start = ap_const_logic_0) or (ap_done_reg = ap_const_logic_1))) and (ap_const_logic_1 = ap_CS_fsm_state1))) then
                cols_V_reg_474 <= cols_V_fu_396_p1;
                rows_V_reg_469 <= rows_V_fu_392_p1;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_logic_1 = ap_CS_fsm_state4)) then
                i_V_reg_503 <= i_V_fu_414_p2;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_logic_1 = ap_CS_fsm_pp1_stage0) and (ap_const_boolean_0 = ap_block_pp1_stage0_11001))) then
                icmp_ln73_reg_508 <= icmp_ln73_fu_420_p2;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_logic_1 = ap_CS_fsm_pp1_stage0) and (ap_const_boolean_0 = ap_block_pp1_stage0_11001) and (icmp_ln73_fu_420_p2 = ap_const_lv1_0))) then
                tmp_31_reg_526 <= ap_phi_mux_p_Val2_s_phi_fu_340_p4(15 downto 8);
                tmp_32_reg_531 <= ap_phi_mux_p_Val2_s_phi_fu_340_p4(23 downto 16);
                tmp_reg_521 <= tmp_fu_440_p1;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((video_src_TVALID_int = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state2))) then
                tmp_data_V_reg_479 <= video_src_TDATA_int;
                tmp_last_V_reg_487 <= video_src_TLAST_int;
            end if;
        end if;
    end process;

    ap_NS_fsm_assign_proc : process (real_start, ap_done_reg, ap_CS_fsm, ap_CS_fsm_state1, img_rows_V_empty_n, img_cols_V_empty_n, img_rows_V_out_full_n, img_cols_V_out_full_n, ap_CS_fsm_state2, ap_enable_reg_pp1_iter0, icmp_ln73_fu_420_p2, ap_CS_fsm_state8, ap_phi_mux_eol_2_i_phi_fu_375_p4, icmp_ln71_fu_409_p2, ap_CS_fsm_state4, ap_block_pp1_stage0_subdone, eol_2_i_reg_372, tmp_user_V_fu_400_p1, video_src_TVALID_int)
    begin
        case ap_CS_fsm is
            when ap_ST_fsm_state1 => 
                if ((not(((img_cols_V_out_full_n = ap_const_logic_0) or (img_rows_V_out_full_n = ap_const_logic_0) or (img_cols_V_empty_n = ap_const_logic_0) or (img_rows_V_empty_n = ap_const_logic_0) or (real_start = ap_const_logic_0) or (ap_done_reg = ap_const_logic_1))) and (ap_const_logic_1 = ap_CS_fsm_state1))) then
                    ap_NS_fsm <= ap_ST_fsm_state2;
                else
                    ap_NS_fsm <= ap_ST_fsm_state1;
                end if;
            when ap_ST_fsm_state2 => 
                if (((video_src_TVALID_int = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state2) and (tmp_user_V_fu_400_p1 = ap_const_lv1_0))) then
                    ap_NS_fsm <= ap_ST_fsm_state2;
                elsif (((video_src_TVALID_int = ap_const_logic_1) and (tmp_user_V_fu_400_p1 = ap_const_lv1_1) and (ap_const_logic_1 = ap_CS_fsm_state2))) then
                    ap_NS_fsm <= ap_ST_fsm_state3;
                else
                    ap_NS_fsm <= ap_ST_fsm_state2;
                end if;
            when ap_ST_fsm_state3 => 
                ap_NS_fsm <= ap_ST_fsm_state4;
            when ap_ST_fsm_state4 => 
                if (((ap_const_logic_1 = ap_CS_fsm_state4) and (icmp_ln71_fu_409_p2 = ap_const_lv1_1))) then
                    ap_NS_fsm <= ap_ST_fsm_state1;
                else
                    ap_NS_fsm <= ap_ST_fsm_pp1_stage0;
                end if;
            when ap_ST_fsm_pp1_stage0 => 
                if (not(((ap_const_boolean_0 = ap_block_pp1_stage0_subdone) and (ap_enable_reg_pp1_iter0 = ap_const_logic_1) and (icmp_ln73_fu_420_p2 = ap_const_lv1_1)))) then
                    ap_NS_fsm <= ap_ST_fsm_pp1_stage0;
                elsif (((ap_const_boolean_0 = ap_block_pp1_stage0_subdone) and (ap_enable_reg_pp1_iter0 = ap_const_logic_1) and (icmp_ln73_fu_420_p2 = ap_const_lv1_1))) then
                    ap_NS_fsm <= ap_ST_fsm_state7;
                else
                    ap_NS_fsm <= ap_ST_fsm_pp1_stage0;
                end if;
            when ap_ST_fsm_state7 => 
                ap_NS_fsm <= ap_ST_fsm_state8;
            when ap_ST_fsm_state8 => 
                if ((not(((video_src_TVALID_int = ap_const_logic_0) and (eol_2_i_reg_372 = ap_const_lv1_0))) and (ap_const_logic_1 = ap_CS_fsm_state8) and (eol_2_i_reg_372 = ap_const_lv1_0))) then
                    ap_NS_fsm <= ap_ST_fsm_state8;
                elsif ((not(((video_src_TVALID_int = ap_const_logic_0) and (eol_2_i_reg_372 = ap_const_lv1_0))) and (ap_const_logic_1 = ap_CS_fsm_state8) and (ap_phi_mux_eol_2_i_phi_fu_375_p4 = ap_const_lv1_1))) then
                    ap_NS_fsm <= ap_ST_fsm_state9;
                else
                    ap_NS_fsm <= ap_ST_fsm_state8;
                end if;
            when ap_ST_fsm_state9 => 
                ap_NS_fsm <= ap_ST_fsm_state4;
            when others =>  
                ap_NS_fsm <= "XXXXXXXX";
        end case;
    end process;
    ap_CS_fsm_pp1_stage0 <= ap_CS_fsm(4);
    ap_CS_fsm_state1 <= ap_CS_fsm(0);
    ap_CS_fsm_state2 <= ap_CS_fsm(1);
    ap_CS_fsm_state3 <= ap_CS_fsm(2);
    ap_CS_fsm_state4 <= ap_CS_fsm(3);
    ap_CS_fsm_state7 <= ap_CS_fsm(5);
    ap_CS_fsm_state8 <= ap_CS_fsm(6);
    ap_CS_fsm_state9 <= ap_CS_fsm(7);
        ap_block_pp1_stage0 <= not((ap_const_boolean_1 = ap_const_boolean_1));

    ap_block_pp1_stage0_01001_assign_proc : process(img_data_stream_0_V_full_n, img_data_stream_1_V_full_n, img_data_stream_2_V_full_n, ap_enable_reg_pp1_iter0, ap_enable_reg_pp1_iter1, icmp_ln73_reg_508, ap_predicate_op67_read_state5, video_src_TVALID_int)
    begin
                ap_block_pp1_stage0_01001 <= (((video_src_TVALID_int = ap_const_logic_0) and (ap_enable_reg_pp1_iter0 = ap_const_logic_1) and (ap_predicate_op67_read_state5 = ap_const_boolean_1)) or ((ap_enable_reg_pp1_iter1 = ap_const_logic_1) and (((img_data_stream_2_V_full_n = ap_const_logic_0) and (icmp_ln73_reg_508 = ap_const_lv1_0)) or ((img_data_stream_1_V_full_n = ap_const_logic_0) and (icmp_ln73_reg_508 = ap_const_lv1_0)) or ((img_data_stream_0_V_full_n = ap_const_logic_0) and (icmp_ln73_reg_508 = ap_const_lv1_0)))));
    end process;


    ap_block_pp1_stage0_11001_assign_proc : process(img_data_stream_0_V_full_n, img_data_stream_1_V_full_n, img_data_stream_2_V_full_n, ap_enable_reg_pp1_iter0, ap_enable_reg_pp1_iter1, icmp_ln73_reg_508, ap_predicate_op67_read_state5, video_src_TVALID_int)
    begin
                ap_block_pp1_stage0_11001 <= (((video_src_TVALID_int = ap_const_logic_0) and (ap_enable_reg_pp1_iter0 = ap_const_logic_1) and (ap_predicate_op67_read_state5 = ap_const_boolean_1)) or ((ap_enable_reg_pp1_iter1 = ap_const_logic_1) and (((img_data_stream_2_V_full_n = ap_const_logic_0) and (icmp_ln73_reg_508 = ap_const_lv1_0)) or ((img_data_stream_1_V_full_n = ap_const_logic_0) and (icmp_ln73_reg_508 = ap_const_lv1_0)) or ((img_data_stream_0_V_full_n = ap_const_logic_0) and (icmp_ln73_reg_508 = ap_const_lv1_0)))));
    end process;


    ap_block_pp1_stage0_subdone_assign_proc : process(img_data_stream_0_V_full_n, img_data_stream_1_V_full_n, img_data_stream_2_V_full_n, ap_enable_reg_pp1_iter0, ap_enable_reg_pp1_iter1, icmp_ln73_reg_508, ap_predicate_op67_read_state5, video_src_TVALID_int)
    begin
                ap_block_pp1_stage0_subdone <= (((video_src_TVALID_int = ap_const_logic_0) and (ap_enable_reg_pp1_iter0 = ap_const_logic_1) and (ap_predicate_op67_read_state5 = ap_const_boolean_1)) or ((ap_enable_reg_pp1_iter1 = ap_const_logic_1) and (((img_data_stream_2_V_full_n = ap_const_logic_0) and (icmp_ln73_reg_508 = ap_const_lv1_0)) or ((img_data_stream_1_V_full_n = ap_const_logic_0) and (icmp_ln73_reg_508 = ap_const_lv1_0)) or ((img_data_stream_0_V_full_n = ap_const_logic_0) and (icmp_ln73_reg_508 = ap_const_lv1_0)))));
    end process;


    ap_block_state1_assign_proc : process(real_start, ap_done_reg, img_rows_V_empty_n, img_cols_V_empty_n, img_rows_V_out_full_n, img_cols_V_out_full_n)
    begin
                ap_block_state1 <= ((img_cols_V_out_full_n = ap_const_logic_0) or (img_rows_V_out_full_n = ap_const_logic_0) or (img_cols_V_empty_n = ap_const_logic_0) or (img_rows_V_empty_n = ap_const_logic_0) or (real_start = ap_const_logic_0) or (ap_done_reg = ap_const_logic_1));
    end process;


    ap_block_state5_pp1_stage0_iter0_assign_proc : process(ap_predicate_op67_read_state5, video_src_TVALID_int)
    begin
                ap_block_state5_pp1_stage0_iter0 <= ((video_src_TVALID_int = ap_const_logic_0) and (ap_predicate_op67_read_state5 = ap_const_boolean_1));
    end process;


    ap_block_state6_pp1_stage0_iter1_assign_proc : process(img_data_stream_0_V_full_n, img_data_stream_1_V_full_n, img_data_stream_2_V_full_n, icmp_ln73_reg_508)
    begin
                ap_block_state6_pp1_stage0_iter1 <= (((img_data_stream_2_V_full_n = ap_const_logic_0) and (icmp_ln73_reg_508 = ap_const_lv1_0)) or ((img_data_stream_1_V_full_n = ap_const_logic_0) and (icmp_ln73_reg_508 = ap_const_lv1_0)) or ((img_data_stream_0_V_full_n = ap_const_logic_0) and (icmp_ln73_reg_508 = ap_const_lv1_0)));
    end process;


    ap_block_state8_assign_proc : process(eol_2_i_reg_372, video_src_TVALID_int)
    begin
                ap_block_state8 <= ((video_src_TVALID_int = ap_const_logic_0) and (eol_2_i_reg_372 = ap_const_lv1_0));
    end process;


    ap_condition_200_assign_proc : process(ap_CS_fsm_pp1_stage0, ap_enable_reg_pp1_iter0, ap_block_pp1_stage0_11001)
    begin
                ap_condition_200 <= ((ap_enable_reg_pp1_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp1_stage0) and (ap_const_boolean_0 = ap_block_pp1_stage0_11001));
    end process;


    ap_condition_pp1_exit_iter0_state5_assign_proc : process(icmp_ln73_fu_420_p2)
    begin
        if ((icmp_ln73_fu_420_p2 = ap_const_lv1_1)) then 
            ap_condition_pp1_exit_iter0_state5 <= ap_const_logic_1;
        else 
            ap_condition_pp1_exit_iter0_state5 <= ap_const_logic_0;
        end if; 
    end process;


    ap_done_assign_proc : process(ap_done_reg, icmp_ln71_fu_409_p2, ap_CS_fsm_state4)
    begin
        if (((ap_const_logic_1 = ap_CS_fsm_state4) and (icmp_ln71_fu_409_p2 = ap_const_lv1_1))) then 
            ap_done <= ap_const_logic_1;
        else 
            ap_done <= ap_done_reg;
        end if; 
    end process;

    ap_enable_pp1 <= (ap_idle_pp1 xor ap_const_logic_1);

    ap_idle_assign_proc : process(real_start, ap_CS_fsm_state1)
    begin
        if (((real_start = ap_const_logic_0) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
            ap_idle <= ap_const_logic_1;
        else 
            ap_idle <= ap_const_logic_0;
        end if; 
    end process;


    ap_idle_pp1_assign_proc : process(ap_enable_reg_pp1_iter0, ap_enable_reg_pp1_iter1)
    begin
        if (((ap_enable_reg_pp1_iter0 = ap_const_logic_0) and (ap_enable_reg_pp1_iter1 = ap_const_logic_0))) then 
            ap_idle_pp1 <= ap_const_logic_1;
        else 
            ap_idle_pp1 <= ap_const_logic_0;
        end if; 
    end process;


    ap_phi_mux_axi_data_V_1_i_phi_fu_292_p4_assign_proc : process(ap_CS_fsm_pp1_stage0, ap_block_pp1_stage0, ap_enable_reg_pp1_iter1, icmp_ln73_reg_508, axi_data_V_1_i_reg_289, p_Val2_s_reg_336)
    begin
        if (((ap_const_boolean_0 = ap_block_pp1_stage0) and (ap_const_logic_1 = ap_CS_fsm_pp1_stage0) and (ap_enable_reg_pp1_iter1 = ap_const_logic_1) and (icmp_ln73_reg_508 = ap_const_lv1_0))) then 
            ap_phi_mux_axi_data_V_1_i_phi_fu_292_p4 <= p_Val2_s_reg_336;
        else 
            ap_phi_mux_axi_data_V_1_i_phi_fu_292_p4 <= axi_data_V_1_i_reg_289;
        end if; 
    end process;


    ap_phi_mux_eol_0_i_phi_fu_315_p4_assign_proc : process(ap_CS_fsm_pp1_stage0, ap_block_pp1_stage0, ap_enable_reg_pp1_iter1, icmp_ln73_reg_508, eol_0_i_reg_311, axi_last_V_2_i_reg_323)
    begin
        if (((ap_const_boolean_0 = ap_block_pp1_stage0) and (ap_const_logic_1 = ap_CS_fsm_pp1_stage0) and (ap_enable_reg_pp1_iter1 = ap_const_logic_1) and (icmp_ln73_reg_508 = ap_const_lv1_0))) then 
            ap_phi_mux_eol_0_i_phi_fu_315_p4 <= axi_last_V_2_i_reg_323;
        else 
            ap_phi_mux_eol_0_i_phi_fu_315_p4 <= eol_0_i_reg_311;
        end if; 
    end process;

    ap_phi_mux_eol_2_i_phi_fu_375_p4 <= eol_2_i_reg_372;

    ap_phi_mux_eol_phi_fu_281_p4_assign_proc : process(ap_CS_fsm_pp1_stage0, ap_block_pp1_stage0, ap_enable_reg_pp1_iter1, icmp_ln73_reg_508, eol_reg_278, axi_last_V_2_i_reg_323)
    begin
        if (((ap_const_boolean_0 = ap_block_pp1_stage0) and (ap_const_logic_1 = ap_CS_fsm_pp1_stage0) and (ap_enable_reg_pp1_iter1 = ap_const_logic_1) and (icmp_ln73_reg_508 = ap_const_lv1_0))) then 
            ap_phi_mux_eol_phi_fu_281_p4 <= axi_last_V_2_i_reg_323;
        else 
            ap_phi_mux_eol_phi_fu_281_p4 <= eol_reg_278;
        end if; 
    end process;


    ap_phi_mux_p_Val2_s_phi_fu_340_p4_assign_proc : process(icmp_ln73_fu_420_p2, or_ln76_fu_434_p2, ap_phi_mux_axi_data_V_1_i_phi_fu_292_p4, ap_phi_reg_pp1_iter0_p_Val2_s_reg_336, video_src_TDATA_int)
    begin
        if ((icmp_ln73_fu_420_p2 = ap_const_lv1_0)) then
            if ((or_ln76_fu_434_p2 = ap_const_lv1_1)) then 
                ap_phi_mux_p_Val2_s_phi_fu_340_p4 <= ap_phi_mux_axi_data_V_1_i_phi_fu_292_p4;
            elsif ((or_ln76_fu_434_p2 = ap_const_lv1_0)) then 
                ap_phi_mux_p_Val2_s_phi_fu_340_p4 <= video_src_TDATA_int;
            else 
                ap_phi_mux_p_Val2_s_phi_fu_340_p4 <= ap_phi_reg_pp1_iter0_p_Val2_s_reg_336;
            end if;
        else 
            ap_phi_mux_p_Val2_s_phi_fu_340_p4 <= ap_phi_reg_pp1_iter0_p_Val2_s_reg_336;
        end if; 
    end process;

    ap_phi_reg_pp1_iter0_axi_last_V_2_i_reg_323 <= "X";
    ap_phi_reg_pp1_iter0_p_Val2_s_reg_336 <= "XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX";

    ap_predicate_op67_read_state5_assign_proc : process(icmp_ln73_fu_420_p2, or_ln76_fu_434_p2)
    begin
                ap_predicate_op67_read_state5 <= ((or_ln76_fu_434_p2 = ap_const_lv1_0) and (icmp_ln73_fu_420_p2 = ap_const_lv1_0));
    end process;

    ap_ready <= internal_ap_ready;
    cols_V_fu_396_p0 <= img_cols_V_dout;
        cols_V_fu_396_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(cols_V_fu_396_p0),32));

    i_V_fu_414_p2 <= std_logic_vector(unsigned(t_V_reg_267) + unsigned(ap_const_lv32_1));
    icmp_ln71_fu_409_p2 <= "1" when (t_V_reg_267 = rows_V_reg_469) else "0";
    icmp_ln73_fu_420_p2 <= "1" when (t_V_12_reg_300 = cols_V_reg_474) else "0";

    img_cols_V_blk_n_assign_proc : process(real_start, ap_done_reg, ap_CS_fsm_state1, img_cols_V_empty_n)
    begin
        if ((not(((real_start = ap_const_logic_0) or (ap_done_reg = ap_const_logic_1))) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
            img_cols_V_blk_n <= img_cols_V_empty_n;
        else 
            img_cols_V_blk_n <= ap_const_logic_1;
        end if; 
    end process;


    img_cols_V_out_blk_n_assign_proc : process(real_start, ap_done_reg, ap_CS_fsm_state1, img_cols_V_out_full_n)
    begin
        if ((not(((real_start = ap_const_logic_0) or (ap_done_reg = ap_const_logic_1))) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
            img_cols_V_out_blk_n <= img_cols_V_out_full_n;
        else 
            img_cols_V_out_blk_n <= ap_const_logic_1;
        end if; 
    end process;

    img_cols_V_out_din <= img_cols_V_dout;

    img_cols_V_out_write_assign_proc : process(real_start, ap_done_reg, ap_CS_fsm_state1, img_rows_V_empty_n, img_cols_V_empty_n, img_rows_V_out_full_n, img_cols_V_out_full_n)
    begin
        if ((not(((img_cols_V_out_full_n = ap_const_logic_0) or (img_rows_V_out_full_n = ap_const_logic_0) or (img_cols_V_empty_n = ap_const_logic_0) or (img_rows_V_empty_n = ap_const_logic_0) or (real_start = ap_const_logic_0) or (ap_done_reg = ap_const_logic_1))) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
            img_cols_V_out_write <= ap_const_logic_1;
        else 
            img_cols_V_out_write <= ap_const_logic_0;
        end if; 
    end process;


    img_cols_V_read_assign_proc : process(real_start, ap_done_reg, ap_CS_fsm_state1, img_rows_V_empty_n, img_cols_V_empty_n, img_rows_V_out_full_n, img_cols_V_out_full_n)
    begin
        if ((not(((img_cols_V_out_full_n = ap_const_logic_0) or (img_rows_V_out_full_n = ap_const_logic_0) or (img_cols_V_empty_n = ap_const_logic_0) or (img_rows_V_empty_n = ap_const_logic_0) or (real_start = ap_const_logic_0) or (ap_done_reg = ap_const_logic_1))) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
            img_cols_V_read <= ap_const_logic_1;
        else 
            img_cols_V_read <= ap_const_logic_0;
        end if; 
    end process;


    img_data_stream_0_V_blk_n_assign_proc : process(img_data_stream_0_V_full_n, ap_CS_fsm_pp1_stage0, ap_block_pp1_stage0, ap_enable_reg_pp1_iter1, icmp_ln73_reg_508)
    begin
        if (((ap_const_boolean_0 = ap_block_pp1_stage0) and (ap_const_logic_1 = ap_CS_fsm_pp1_stage0) and (ap_enable_reg_pp1_iter1 = ap_const_logic_1) and (icmp_ln73_reg_508 = ap_const_lv1_0))) then 
            img_data_stream_0_V_blk_n <= img_data_stream_0_V_full_n;
        else 
            img_data_stream_0_V_blk_n <= ap_const_logic_1;
        end if; 
    end process;

    img_data_stream_0_V_din <= tmp_reg_521;

    img_data_stream_0_V_write_assign_proc : process(ap_CS_fsm_pp1_stage0, ap_enable_reg_pp1_iter1, icmp_ln73_reg_508, ap_block_pp1_stage0_11001)
    begin
        if (((ap_const_logic_1 = ap_CS_fsm_pp1_stage0) and (ap_enable_reg_pp1_iter1 = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp1_stage0_11001) and (icmp_ln73_reg_508 = ap_const_lv1_0))) then 
            img_data_stream_0_V_write <= ap_const_logic_1;
        else 
            img_data_stream_0_V_write <= ap_const_logic_0;
        end if; 
    end process;


    img_data_stream_1_V_blk_n_assign_proc : process(img_data_stream_1_V_full_n, ap_CS_fsm_pp1_stage0, ap_block_pp1_stage0, ap_enable_reg_pp1_iter1, icmp_ln73_reg_508)
    begin
        if (((ap_const_boolean_0 = ap_block_pp1_stage0) and (ap_const_logic_1 = ap_CS_fsm_pp1_stage0) and (ap_enable_reg_pp1_iter1 = ap_const_logic_1) and (icmp_ln73_reg_508 = ap_const_lv1_0))) then 
            img_data_stream_1_V_blk_n <= img_data_stream_1_V_full_n;
        else 
            img_data_stream_1_V_blk_n <= ap_const_logic_1;
        end if; 
    end process;

    img_data_stream_1_V_din <= tmp_31_reg_526;

    img_data_stream_1_V_write_assign_proc : process(ap_CS_fsm_pp1_stage0, ap_enable_reg_pp1_iter1, icmp_ln73_reg_508, ap_block_pp1_stage0_11001)
    begin
        if (((ap_const_logic_1 = ap_CS_fsm_pp1_stage0) and (ap_enable_reg_pp1_iter1 = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp1_stage0_11001) and (icmp_ln73_reg_508 = ap_const_lv1_0))) then 
            img_data_stream_1_V_write <= ap_const_logic_1;
        else 
            img_data_stream_1_V_write <= ap_const_logic_0;
        end if; 
    end process;


    img_data_stream_2_V_blk_n_assign_proc : process(img_data_stream_2_V_full_n, ap_CS_fsm_pp1_stage0, ap_block_pp1_stage0, ap_enable_reg_pp1_iter1, icmp_ln73_reg_508)
    begin
        if (((ap_const_boolean_0 = ap_block_pp1_stage0) and (ap_const_logic_1 = ap_CS_fsm_pp1_stage0) and (ap_enable_reg_pp1_iter1 = ap_const_logic_1) and (icmp_ln73_reg_508 = ap_const_lv1_0))) then 
            img_data_stream_2_V_blk_n <= img_data_stream_2_V_full_n;
        else 
            img_data_stream_2_V_blk_n <= ap_const_logic_1;
        end if; 
    end process;

    img_data_stream_2_V_din <= tmp_32_reg_531;

    img_data_stream_2_V_write_assign_proc : process(ap_CS_fsm_pp1_stage0, ap_enable_reg_pp1_iter1, icmp_ln73_reg_508, ap_block_pp1_stage0_11001)
    begin
        if (((ap_const_logic_1 = ap_CS_fsm_pp1_stage0) and (ap_enable_reg_pp1_iter1 = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp1_stage0_11001) and (icmp_ln73_reg_508 = ap_const_lv1_0))) then 
            img_data_stream_2_V_write <= ap_const_logic_1;
        else 
            img_data_stream_2_V_write <= ap_const_logic_0;
        end if; 
    end process;


    img_rows_V_blk_n_assign_proc : process(real_start, ap_done_reg, ap_CS_fsm_state1, img_rows_V_empty_n)
    begin
        if ((not(((real_start = ap_const_logic_0) or (ap_done_reg = ap_const_logic_1))) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
            img_rows_V_blk_n <= img_rows_V_empty_n;
        else 
            img_rows_V_blk_n <= ap_const_logic_1;
        end if; 
    end process;


    img_rows_V_out_blk_n_assign_proc : process(real_start, ap_done_reg, ap_CS_fsm_state1, img_rows_V_out_full_n)
    begin
        if ((not(((real_start = ap_const_logic_0) or (ap_done_reg = ap_const_logic_1))) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
            img_rows_V_out_blk_n <= img_rows_V_out_full_n;
        else 
            img_rows_V_out_blk_n <= ap_const_logic_1;
        end if; 
    end process;

    img_rows_V_out_din <= img_rows_V_dout;

    img_rows_V_out_write_assign_proc : process(real_start, ap_done_reg, ap_CS_fsm_state1, img_rows_V_empty_n, img_cols_V_empty_n, img_rows_V_out_full_n, img_cols_V_out_full_n)
    begin
        if ((not(((img_cols_V_out_full_n = ap_const_logic_0) or (img_rows_V_out_full_n = ap_const_logic_0) or (img_cols_V_empty_n = ap_const_logic_0) or (img_rows_V_empty_n = ap_const_logic_0) or (real_start = ap_const_logic_0) or (ap_done_reg = ap_const_logic_1))) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
            img_rows_V_out_write <= ap_const_logic_1;
        else 
            img_rows_V_out_write <= ap_const_logic_0;
        end if; 
    end process;


    img_rows_V_read_assign_proc : process(real_start, ap_done_reg, ap_CS_fsm_state1, img_rows_V_empty_n, img_cols_V_empty_n, img_rows_V_out_full_n, img_cols_V_out_full_n)
    begin
        if ((not(((img_cols_V_out_full_n = ap_const_logic_0) or (img_rows_V_out_full_n = ap_const_logic_0) or (img_cols_V_empty_n = ap_const_logic_0) or (img_rows_V_empty_n = ap_const_logic_0) or (real_start = ap_const_logic_0) or (ap_done_reg = ap_const_logic_1))) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
            img_rows_V_read <= ap_const_logic_1;
        else 
            img_rows_V_read <= ap_const_logic_0;
        end if; 
    end process;


    internal_ap_ready_assign_proc : process(icmp_ln71_fu_409_p2, ap_CS_fsm_state4)
    begin
        if (((ap_const_logic_1 = ap_CS_fsm_state4) and (icmp_ln71_fu_409_p2 = ap_const_lv1_1))) then 
            internal_ap_ready <= ap_const_logic_1;
        else 
            internal_ap_ready <= ap_const_logic_0;
        end if; 
    end process;

    j_V_fu_425_p2 <= std_logic_vector(unsigned(t_V_12_reg_300) + unsigned(ap_const_lv32_1));
    or_ln76_fu_434_p2 <= (sof_1_i_fu_176 or ap_phi_mux_eol_0_i_phi_fu_315_p4);

    real_start_assign_proc : process(ap_start, start_full_n, start_once_reg)
    begin
        if (((start_once_reg = ap_const_logic_0) and (start_full_n = ap_const_logic_0))) then 
            real_start <= ap_const_logic_0;
        else 
            real_start <= ap_start;
        end if; 
    end process;

    rows_V_fu_392_p0 <= img_rows_V_dout;
        rows_V_fu_392_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(rows_V_fu_392_p0),32));

    start_out <= real_start;

    start_write_assign_proc : process(real_start, start_once_reg)
    begin
        if (((start_once_reg = ap_const_logic_0) and (real_start = ap_const_logic_1))) then 
            start_write <= ap_const_logic_1;
        else 
            start_write <= ap_const_logic_0;
        end if; 
    end process;

    tmp_fu_440_p1 <= ap_phi_mux_p_Val2_s_phi_fu_340_p4(8 - 1 downto 0);
    tmp_user_V_fu_400_p1 <= video_src_TUSER_int;

    video_src_TDATA_blk_n_assign_proc : process(ap_CS_fsm_state2, ap_CS_fsm_pp1_stage0, ap_enable_reg_pp1_iter0, ap_block_pp1_stage0, icmp_ln73_fu_420_p2, or_ln76_fu_434_p2, ap_CS_fsm_state8, eol_2_i_reg_372, video_src_TVALID_int)
    begin
        if (((ap_const_logic_1 = ap_CS_fsm_state2) or ((ap_const_boolean_0 = ap_block_pp1_stage0) and (ap_enable_reg_pp1_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp1_stage0) and (or_ln76_fu_434_p2 = ap_const_lv1_0) and (icmp_ln73_fu_420_p2 = ap_const_lv1_0)) or ((ap_const_logic_1 = ap_CS_fsm_state8) and (eol_2_i_reg_372 = ap_const_lv1_0)))) then 
            video_src_TDATA_blk_n <= video_src_TVALID_int;
        else 
            video_src_TDATA_blk_n <= ap_const_logic_1;
        end if; 
    end process;


    video_src_TREADY_assign_proc : process(video_src_TVALID, regslice_both_AXI_video_strm_V_data_V_U_ack_in)
    begin
        if (((video_src_TVALID = ap_const_logic_1) and (regslice_both_AXI_video_strm_V_data_V_U_ack_in = ap_const_logic_1))) then 
            video_src_TREADY <= ap_const_logic_1;
        else 
            video_src_TREADY <= ap_const_logic_0;
        end if; 
    end process;


    video_src_TREADY_int_assign_proc : process(ap_CS_fsm_state2, ap_CS_fsm_pp1_stage0, ap_enable_reg_pp1_iter0, ap_CS_fsm_state8, ap_predicate_op67_read_state5, ap_block_pp1_stage0_11001, eol_2_i_reg_372, video_src_TVALID_int)
    begin
        if ((((ap_enable_reg_pp1_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp1_stage0) and (ap_predicate_op67_read_state5 = ap_const_boolean_1) and (ap_const_boolean_0 = ap_block_pp1_stage0_11001)) or ((video_src_TVALID_int = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state2)) or (not(((video_src_TVALID_int = ap_const_logic_0) and (eol_2_i_reg_372 = ap_const_lv1_0))) and (ap_const_logic_1 = ap_CS_fsm_state8) and (eol_2_i_reg_372 = ap_const_lv1_0)))) then 
            video_src_TREADY_int <= ap_const_logic_1;
        else 
            video_src_TREADY_int <= ap_const_logic_0;
        end if; 
    end process;

end behav;
